const ids = {
    CHECKBOX: "checkbox",
    NAME: "name",
    OWNER: "owner",
    APP: "app",
    START_DATE: "start_date",
    END_DATE: "end_date",
    DURATION: "duration",
    STATUS: "status",
    ACTIONS: "actions",
    TOOLBAR: "menuBar",
    PARAMETERS: "parameters",
    TYPE: "type",
    VALUE: "value",
    JOB_ID: "jobId",
    ANALYSES_VIEW: ".analysesView",
    LISTING_TABLE: "listingTable",
    HEADER: "header",
    GRID_VIEW_BTN: "gridViewBtn",
    TABLE_VIEW_BTN: "tableViewBtn",
    TOOLTIP: "tooltip",
    BUTTON: "button",
    ANALYSES_NAVIGATION: "analysesNavigation",
    CLEAR_FILTER: "clearBatchAnalysesFilter",
    VIEW_FILTER_FIELD: "viewFilterTextInputField",
    APP_TYPE_FILTER_FIELD: "appTypeFilterTextInputFiled",
    VIEW_FILTER: "viewFilter",
    APP_TYPE_FILTER: "appTypeFilter",

    MENUITEM_ANALYSES: "analyses",
    MENUITEM_GO_TO_FOLDER: "goToFolder",
    MENUITEM_VIEW_LOGS: "goToLogs",
    MENUITEM_VIEW_PARAMS: "viewParams",
    MENUITEM_VIEW_ANALYSES_INFO: "viewInfo",
    MENUITEM_RELAUNCH: "relaunch",
    MENUITEM_DELETE: "delete",
    MENUITEM_CANCEL: "cancel",
    MENUITEM_EDIT: "edit",
    MENUITEM_RENAME: "rename",
    MENUITEM_UPDATE_COMMENTS: "updateComments",
    MENUITEM_SHARE_COLLAB: "sharecollab",
    MENUITEM_SHARE_SUPPORT: "sharesupport",
    MENUITEM_DETAILS: "details",
    MENUITEM_BATCH_FILTER: "viewBatchDetails",
    MENUITEM_GOTO_VICE: "gotoVICE",
    MENUITEM_EXTEND_TIME_LIMIT: "extendTimeLimit",
    MENUITEM_FILTER: "filters",
    MENUITEM_ADD_TO_BAG: "addToBag",
    MENUITEM_REFRESH: "refresh",
    MENUITEM_GOTO_ANALYSES: "gotoAnalyses",
    MENUITEM_GOTO_APPS: "gotoApps",
    MENUITEM_SHARE_WITH_SUPPORT: "shareWithSupport",

    CANCEL_BTN: "cancelBtn",
    DETAILS_BTN: "detailsBtn",
    ADD_TO_BAG_BTN: "addToBagBtn",
    REFRESH_BTN: "refreshBtn",

    VIEW_PARAMS: ".viewParamsView",

    BUTTON_REFRESH: "refresh",

    FIELD_SEARCH: "search",

    ANALYSIS_DOT_MENU: "dotMenu",
    GRID: "grid",
    MENUBAR: "menuBar",
    ANALYSIS_NAME_CELL: "nameCell",
    ANALYSIS_ACTIONS_CELL: "actionsCell",
    APP_NAME_CELL: "appNameCell",
    SUPPORT_CELL: "supportCell",
    SHARE_WITH_SUPPORT: "shareWithSupport",
    COMMENTS: "comments",

    PERMISSIONS: "permissions",
    APP_TYPE: "appType",

    ALL: "all",
    MINE: "mine",
    THEIRS: "theirs",

    AGAVE: "agave",
    DE: "de",
    INTERACTIVE: "interactive",
    OSG: "osg",

    DIALOG: {
        DELETE: "delete",
        CANCEL: "cancel",
        COMMENT: "comment",
        MORE_HELP: "moreHelp",
        RELAUNCH: "relaunch",
        RENAME: "rename",
        STATUS_HELP: "statusHelp",
        SUBMIT: "submit",
        CLOSE: "close",
    },

    ICONS: {
        INTERACTIVE: "interactive",
        BATCH: "batch",
        COLLAPSE: "collapse",
        OUTPUT: "output",
        HELP: "help",
        RELAUNCH: "relaunch",
        TIME_LIMIT: "timeLimit",
        LOGS: "logs",
    },

    INFO: {
        TIMESTAMP: "timestamp",
        MESSAGE: "message",
        STATUS: "status",
        INFO: "info",
        EXPAND: "expandIcon",
        STEP: "step",
        UPDATE: "update",
    },

    VICE_LOGS_VIEWER: {
        VIEWER: "viceLogViewer",
        FOLLOW_LOGS: "followLogs",
        REFRESH: "refresh",
    },

    TERMINATE_ANALYSIS_DLG: "terminateAnalysisDlg",
    TERMINATE_BTN: "terminateBtn",
    PENDING_TERMINATION_DLG: "pendingTerminationDlg",

    STATUS_HISTORY_PANEL: "statusHistoryPanel",
    STATUS_HISTORY_PANEL_HEADER: "statusHistoryPanelHeader",
    PARAMETERS_PANEL_HEADER: "parametersPanelHeader",
    PARAMETERS_PANEL: "parametersPanel",
    BATCH_PANEL_HEADER: "batchPanelHeader",
    BATCH_PANEL: "batchPanel",
};

export default ids;
