export default {
    BASEID: "bag",
    DIALOG: "dialog",
    DOWNLOAD: "download",
    SHARE: "share",
    CLEARALL: "clearall",
    CLOSE: "close",
    HELP: "help",
    BUTTON: "button",
    MENU: "menu",
    BADGE: "badge",
    TITLE: "title",
    LIST: "list",
    FILTER: "filter",
    SELECT: "select",
    LABEL: "label",
    AVATAR: "avatar",
    DELETE: "delete",
    FILTERBY: {
        ALL: "all",
        DOWNLOADABLE: "downloadable",
        SHAREABLE: "shareable",
    },
};
