export const JoinTeamDenialNotification = {
    deleted: false,
    email: true,
    email_template: "team_join_denial",
    message: {
        id: "c2547d9a-6ca4-11eb-9f56-62d47aced14b",
        text: "Team join request denied",
        timestamp: "1613074045560",
    },
    payload: {
        action: "team_join_denial",
        admin_message: "Superheroes only!",
        email_address: "ipcdev@cyverse.org",
        team_name: "batman:heroes",
    },
    seen: true,
    subject: "Team join request denied",
    type: "team",
    user: "ipcdev",
};

export const AdminTeamJoinRequestNotification = {
    deleted: false,
    email: true,
    email_template: "team_join_request",
    message: {
        id: "def1d02c-6bed-11eb-8ef5-62d47aced14b",
        text: 'batman has requested to join team "ipcdev:test_team"',
        timestamp: "1612995495645",
    },
    payload: {
        action: "team_join_request",
        email_address: "batman@cyverse.org",
        requester_email: "batman@cyverse.org",
        requester_id: "batman",
        requester_message: "Let me in!",
        requester_name: "Bruce Wayne",
        team_name: "ipcdev:test_team",
    },
    seen: true,
    subject: 'batman has requested to join team "ipcdev:test_team"',
    type: "team",
    user: "ipcdev",
};

export const mockNotificationsListing = {
    total: "37",
    unseen_total: "5",
    messages: [
        JoinTeamDenialNotification,
        AdminTeamJoinRequestNotification,
        {
            deleted: false,
            email: false,
            payload: {
                action: "empty_trash",
                paths: ["/iplant/trash/home/de-irods/ipcdev"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "Finished emptying trash",
            message: {
                id: "46CB6C8E-882A-432E-8417-9772DBD1BC27",
                timestamp: "1603848541663",
                text: "Finished emptying trash",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "delete",
                paths: ["/iplant/trash/home/de-irods/ipcdev"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "Finished deleting 1 file(s)/folder(s)",
            message: {
                id: "B17C5598-FDEC-45B9-B8C2-AD5BA0927545",
                timestamp: "1603848073751",
                text: "Finished deleting /iplant/trash/home/de-irods/ipcdev/test-trash.5jHQXyi",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "trash",
                paths: [
                    "/iplant/trash/home/de-irods/ipcdev/test-trash.5jHQXyi",
                ],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "Finished moving 1 files(s)/folder(s) to trash",
            message: {
                id: "FD29FA13-B1A1-40CA-9E49-030E44AF8697",
                timestamp: "1603847948660",
                text: "Finished moving /iplant/home/ipcdev/test-trash to trash at /iplant/trash/home/de-irods/ipcdev/test-trash.5jHQXyi",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                access_url: "https://a1cdf86ae.cyverse.run:4343",
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/Copy_of_NanoDJ_analysis1-2020-10-16-21-07-37.7",
                name: "Copy_of_NanoDJ_analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "57712906-d5e7-11e9-869a-008cfa5ae621",
                analysisstartdate: "2020-10-16T21:07:37.763Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Running",
                batch: false,
                enddate: "0",
                status: "Running",
                id: "a13bc61c-0ff3-11eb-a36d-62d47aced14b",
                analysisname: "Copy_of_NanoDJ_analysis1",
                startdate: "1602882457763",
                app_description:
                    "A Dockerized Jupyter Notebook for Interactive Oxford Nanopore MinION Sequence Manipulation and Genome Assembly",
                interactive_urls: ["https://a1cdf86ae.cyverse.run:4343"],
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/Copy_of_NanoDJ_analysis1-2020-10-16-21-07-37.7",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "Copy of NanoDJ",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: false,
            user: "ipcdev",
            subject: "Copy_of_NanoDJ_analysis1 status changed.",
            message: {
                id: "359AF1A1-103A-4DAE-867A-114E74C3AC9D",
                timestamp: "1602882500335",
                text: "Copy_of_NanoDJ_analysis1 running",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/Copy_of_NanoDJ_analysis1-2020-10-16-21-07-37.7",
                name: "Copy_of_NanoDJ_analysis1",
                username: "ipcdev@iplantcollaborative.org",
                app_id: "57712906-d5e7-11e9-869a-008cfa5ae621",
                analysisstartdate: "2020-10-16T21:07:42.157Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Submitted",
                batch: false,
                status: "Submitted",
                id: "a13bc61c-0ff3-11eb-a36d-62d47aced14b",
                analysisname: "Copy_of_NanoDJ_analysis1",
                startdate: "1602882462157",
                app_description:
                    "A Dockerized Jupyter Notebook for Interactive Oxford Nanopore MinION Sequence Manipulation and Genome Assembly",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/Copy_of_NanoDJ_analysis1-2020-10-16-21-07-37.7",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "Copy of NanoDJ",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: false,
            user: "ipcdev",
            subject: "Copy_of_NanoDJ_analysis1 status changed.",
            message: {
                id: "DE24C5EF-68A2-462D-B3FC-B1F06C7AA11B",
                timestamp: "1602882462337",
                text: "Copy_of_NanoDJ_analysis1 submitted",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                email_address: "core-sw@iplantcollaborative.org",
                contents: null,
                uuid: "265abcc2-0f31-11eb-b254-62d47aced14b",
            },
            email_template: "blank",
            type: "permanent id request",
            seen: false,
            user: "ipcdev",
            subject: "DOI Request Submitted for doi-notification-test",
            message: {
                id: "AD8A7971-3D95-4812-BC3B-FF936EC6CF29",
                timestamp: "1602798934273",
                text: "DOI Request Submitted for doi-notification-test",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                description: "count words",
                documentation_url:
                    "https://cyverse.atlassian.net/browse/CORE-1140",
                source_url: "https://cyverse.atlassian.net/browse/CORE-1140",
                architecture: "Others",
                name: "wc",
                comments: "",
                test_data_path:
                    "https://cyverse.atlassian.net/browse/CORE-1140",
                submitted_by: "ipcdev@iplantcollaborative.org",
                history: [
                    {
                        status: "Submitted",
                        status_date: 1602798823038,
                        updated_by: "ipcdev@iplantcollaborative.org",
                        comments: "",
                    },
                ],
                toolname: "wc",
                cmd_line: "https://cyverse.atlassian.net/browse/CORE-1140",
                id: "13bde34a-0c71-405d-97d8-bd2d03685155",
                attribution: "",
                version: "X",
                email_address: "core-sw@iplantcollaborative.org",
            },
            email_template: "tool_request_submitted",
            type: "tool request",
            seen: false,
            user: "ipcdev",
            subject: "Tool Request wc Submitted",
            message: {
                id: "894F6820-7588-45B3-960D-0696F2958A3E",
                timestamp: "1602798823125",
                text: "Tool Request wc Submitted",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                action: "added_to_community",
                email_address: "core-sw@iplantcollaborative.org",
                contents: null,
                team_name: "Dev Test Community",
            },
            email_template: "blank",
            type: "community",
            seen: false,
            user: "ipcdev",
            subject: "Added as community admin to Dev Test Community",
            message: {
                id: "1F6E9355-1EE1-453A-A70E-9E806BC2B7E2",
                timestamp: "1602798755511",
                text: "Added as community admin to Dev Test Community",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                name: "DE_Word_Count_HT-analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                batch_status: {
                    total: 6,
                    completed: 6,
                    running: 0,
                    submitted: 0,
                },
                analysisstartdate: "2020-10-13T23:59:20.617Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Completed",
                batch: true,
                enddate: "1602633680296",
                status: "Completed",
                id: "1c5e8bb8-0db0-11eb-a205-62d47aced14b",
                analysisname: "DE_Word_Count_HT-analysis1",
                startdate: "1602633560617",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_HT-analysis1 status changed.",
            message: {
                id: "B287FC1E-9B4F-43F9-9346-7A93F90D0419",
                timestamp: "1602633680629",
                text: "DE_Word_Count_HT-analysis1 completed",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/wregglej/analyses_qa/DE_Word_Count_analysis1-2020-10-14-00-00-25.2",
                name: "DE_Word_Count_analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "2020-10-14T00:00:25.240Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Failed",
                batch: false,
                enddate: "1602633667091",
                status: "Failed",
                id: "43392e6e-0db0-11eb-9925-62d47aced14b",
                analysisname: "DE_Word_Count_analysis1",
                startdate: "1602633625240",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                wiki_url:
                    "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
                notify: false,
                resultfolderid:
                    "/iplant/home/wregglej/analyses_qa/DE_Word_Count_analysis1-2020-10-14-00-00-25.2",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_analysis1 status changed.",
            message: {
                id: "1743F691-8847-4F30-8C3B-12FE9B331CA4",
                timestamp: "1602633667275",
                text: "DE_Word_Count_analysis1 failed",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/wregglej/analyses_qa/DE_Word_Count_analysis1-2020-10-14-00-00-25.2",
                name: "DE_Word_Count_analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "2020-10-14T00:00:25.240Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Running",
                batch: false,
                enddate: "0",
                status: "Running",
                id: "43392e6e-0db0-11eb-9925-62d47aced14b",
                analysisname: "DE_Word_Count_analysis1",
                startdate: "1602633625240",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                wiki_url:
                    "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
                notify: false,
                resultfolderid:
                    "/iplant/home/wregglej/analyses_qa/DE_Word_Count_analysis1-2020-10-14-00-00-25.2",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_analysis1 status changed.",
            message: {
                id: "4389F9DA-B010-41D1-9237-20F17D2CF5FD",
                timestamp: "1602633642968",
                text: "DE_Word_Count_analysis1 running",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                name: "DE_Word_Count_HT-analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                batch_status: {
                    total: 6,
                    completed: 4,
                    running: 1,
                    submitted: 1,
                },
                analysisstartdate: "2020-10-13T23:59:20.617Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Running",
                batch: true,
                enddate: "1602633638262",
                status: "Running",
                id: "1c5e8bb8-0db0-11eb-a205-62d47aced14b",
                analysisname: "DE_Word_Count_HT-analysis1",
                startdate: "1602633560617",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_HT-analysis1 status changed.",
            message: {
                id: "5BB0FFFC-9860-4A47-8F35-05698FA3084E",
                timestamp: "1602633640009",
                text: "DE_Word_Count_HT-analysis1 running",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                name: "DE_Word_Count_HT-analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                batch_status: {
                    total: 6,
                    completed: 4,
                    running: 0,
                    submitted: 2,
                },
                analysisstartdate: "2020-10-13T23:59:20.617Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Submitted",
                batch: true,
                enddate: "1602633638262",
                status: "Submitted",
                id: "1c5e8bb8-0db0-11eb-a205-62d47aced14b",
                analysisname: "DE_Word_Count_HT-analysis1",
                startdate: "1602633560617",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_HT-analysis1 status changed.",
            message: {
                id: "78F34229-A5B8-437F-8FB8-B0141750D57C",
                timestamp: "1602633638494",
                text: "DE_Word_Count_HT-analysis1 submitted",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder: null,
                job_name: "DE_Word_Count_analysis1",
                username: "wregglej@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "",
                system_id: "de",
                analysisstatus: "Completed",
                end_date: "2020-10-12T19:29:57Z",
                app_wiki_url:
                    "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
                start_date: "2020-10-12T19:29:02Z",
                status: "Completed",
                parent_id: null,
                id: "302b23a8-0cc1-11eb-82dc-62d47aced14b",
                analysisname: null,
                app_description: "Counts the number of words in a file",
                user_id: "6be9d7fe-854a-11e4-b1aa-bb594900dd6f",
                job_type: "DE",
                action: "job_status_change",
                submission: {
                    description: "",
                    requirements: [
                        {
                            min_cpu_cores: 0,
                            min_memory_limit: 0,
                            min_disk_space: 0,
                            step_number: 0,
                        },
                    ],
                    config: {
                        "089a61a0-23d9-4021-9354-a8498ef3ff19_13914010-89cd-406d-99c3-9c4ff8b023c3":
                            "/iplant/home/wregglej/logs/gitignore_global.txt",
                    },
                    name: "DE_Word_Count_analysis1",
                    job_config: {
                        "089a61a0-23d9-4021-9354-a8498ef3ff19_13914010-89cd-406d-99c3-9c4ff8b023c3":
                            "/iplant/home/wregglej/logs/gitignore_global.txt",
                    },
                    app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                    system_id: "de",
                    debug: false,
                    create_output_subdir: true,
                    output_dir: "/iplant/home/wregglej/analyses_qa",
                    notify: false,
                },
                analysisdescription: "",
                notify: false,
                result_folder_path:
                    "/iplant/home/wregglej/analyses_qa/DE_Word_Count_analysis1-2020-10-12-19-29-02.2",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                is_batch: false,
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: " status changed.",
            message: {
                id: "67185A54-9C01-4A9E-AA1C-1C598DE8D760",
                timestamp: "1602633626986",
                text: "3 of 3 analyses successfully relaunched",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                name: "DE_Word_Count_HT-analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                batch_status: {
                    total: 4,
                    completed: 0,
                    running: 1,
                    submitted: 3,
                },
                analysisstartdate: "2020-10-13T23:59:20.617Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Running",
                batch: true,
                enddate: "0",
                status: "Running",
                id: "1c5e8bb8-0db0-11eb-a205-62d47aced14b",
                analysisname: "DE_Word_Count_HT-analysis1",
                startdate: "1602633560617",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_HT-analysis1 status changed.",
            message: {
                id: "6A2CA42D-7A7F-47B0-AB02-26B74E9EF0A1",
                timestamp: "1602633582253",
                text: "DE_Word_Count_HT-analysis1 running",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                name: "DE_Word_Count_HT-analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                batch_status: {
                    total: 4,
                    completed: 0,
                    running: 0,
                    submitted: 4,
                },
                analysisstartdate: "2020-10-13T23:59:20.617Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Submitted",
                batch: true,
                enddate: "0",
                status: "Submitted",
                id: "1c5e8bb8-0db0-11eb-a205-62d47aced14b",
                analysisname: "DE_Word_Count_HT-analysis1",
                startdate: "1602633560617",
                app_description: "Counts the number of words in a file",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_HT-analysis1 status changed.",
            message: {
                id: "F56F53D8-7934-4995-AC42-97EE02127DD5",
                timestamp: "1602633563848",
                text: "DE_Word_Count_HT-analysis1 4 analyses of 4 submitted",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                name: "DE_Word_Count_HT-analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "2020-10-13T23:59:20.617Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Submitted",
                batch: false,
                enddate: "0",
                status: "Submitted",
                id: "1c5e8bb8-0db0-11eb-a205-62d47aced14b",
                analysisname: "DE_Word_Count_HT-analysis1",
                startdate: "1602633560617",
                app_description: "Counts the number of words in a file",
                action: "job_status_change",
                analysisdescription: "",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_HT-analysis1-2020-10-13-23-59-19.6",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_HT-analysis1 status changed.",
            message: {
                id: "40C09FA7-33F4-46D8-A7E0-956C948450B0",
                timestamp: "1602633560761",
                text: "DE_Word_Count_HT-analysis1 submitted",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "UPLOAD_COMPLETE",
                data: {
                    infoType: "",
                    path: "/iplant/home/ipcdev/ht-path.list",
                    parentFolderId: "/iplant/home/ipcdev",
                    "date-created": "1602633529000",
                    md5: "16872b0d4fb409388aac3e5b7d1cdc68",
                    permission: "own",
                    "date-modified": "1602633529000",
                    "file-size": "180",
                    label: "ht-path.list",
                    id: "09c14770-0db0-11eb-878f-fa163ef45956",
                    "content-type": "text/plain",
                    sourceUrl: "ht-path.list",
                },
            },
            email_template: null,
            type: "Data",
            seen: true,
            user: "ipcdev",
            subject: "ht-path.list uploaded successfully.",
            message: {
                id: "65E15AFE-982B-4F2F-B3C8-5CCF8F6068AD",
                timestamp: "1602633530695",
                text: "ht-path.list uploaded successfully.",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_analysis1-2020-10-13-23-58-10.4",
                name: "DE_Word_Count_analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "2020-10-13T23:58:10.493Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Completed",
                batch: false,
                enddate: "1602633529879",
                status: "Completed",
                id: "f2f069cc-0daf-11eb-bfd2-62d47aced14b",
                analysisname: "DE_Word_Count_analysis1",
                startdate: "1602633490493",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                wiki_url:
                    "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_analysis1-2020-10-13-23-58-10.4",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_analysis1 status changed.",
            message: {
                id: "455FB3D5-6884-4A4C-A2C6-3868954E0ECC",
                timestamp: "1602633530149",
                text: "DE_Word_Count_analysis1 completed",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_analysis1-2020-10-13-23-58-10.4",
                name: "DE_Word_Count_analysis1",
                can_share: false,
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "2020-10-13T23:58:10.493Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Running",
                batch: false,
                enddate: "0",
                status: "Running",
                id: "f2f069cc-0daf-11eb-bfd2-62d47aced14b",
                analysisname: "DE_Word_Count_analysis1",
                startdate: "1602633490493",
                app_description: "Counts the number of words in a file",
                user_id: "6c04cd3e-854a-11e4-8fa0-1fbef07e6168",
                action: "job_status_change",
                analysisdescription: "",
                wiki_url:
                    "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_analysis1-2020-10-13-23-58-10.4",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_analysis1 status changed.",
            message: {
                id: "E3D88DB2-ED11-4196-941F-3E3AB52E0E21",
                timestamp: "1602633500603",
                text: "DE_Word_Count_analysis1 running",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                description: "",
                analysisresultsfolder:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_analysis1-2020-10-13-23-58-10.4",
                name: "DE_Word_Count_analysis1",
                username: "ipcdev@iplantcollaborative.org",
                app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
                analysisstartdate: "2020-10-13T23:58:11.131Z",
                system_id: "de",
                app_disabled: false,
                analysisstatus: "Submitted",
                batch: false,
                status: "Submitted",
                id: "f2f069cc-0daf-11eb-bfd2-62d47aced14b",
                analysisname: "DE_Word_Count_analysis1",
                startdate: "1602633491131",
                app_description: "Counts the number of words in a file",
                action: "job_status_change",
                analysisdescription: "",
                wiki_url:
                    "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
                notify: true,
                resultfolderid:
                    "/iplant/home/ipcdev/analyses_qa/DE_Word_Count_analysis1-2020-10-13-23-58-10.4",
                email_address: "core-sw@iplantcollaborative.org",
                user: "ipcdev",
                app_name: "DE Word Count",
            },
            email_template: "analysis_status_change",
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "DE_Word_Count_analysis1 status changed.",
            message: {
                id: "84666127-F0BE-47AF-966E-6FD34B825608",
                timestamp: "1602633491225",
                text: "DE_Word_Count_analysis1 submitted",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "unshare",
                paths: ["/iplant/home/ipcdev/hello-shiny"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "1 file(s)/folder(s) have been unshared with psarando",
            message: {
                id: "2AF6D5DB-21C0-4ED8-926F-96A8FF1AD4C0",
                timestamp: "1602633263489",
                text: " The following file(s)/folder(s) have been unshared with psarando: hello-shiny",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                action: "added_to_team",
                email_address: "core-sw@iplantcollaborative.org",
                team_name: "ipcdev:Dev Team",
            },
            email_template: "added_to_team",
            type: "team",
            seen: true,
            user: "ipcdev",
            subject: "Added to team",
            message: {
                id: "026D5EBA-071A-4F34-A9B3-E7869A87FA6F",
                timestamp: "1602633177357",
                text: "Added to team",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "rename",
                paths: [
                    "/iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/folderwithanevenlongername",
                ],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished renaming /iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/XXfolderwithanevenlongernameXX to folderwithanevenlongername",
            message: {
                id: "DEB0DB55-6AE9-49E3-9F7C-6EB77543D6A5",
                timestamp: "1602633002667",
                text: "Finished renaming /iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/XXfolderwithanevenlongernameXX to /iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/folderwithanevenlongername",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "rename",
                paths: [
                    "/iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/XXfolderwithanevenlongernameXX",
                ],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished renaming /iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/folderwithanevenlongername to XXfolderwithanevenlongernameXX",
            message: {
                id: "2DFB8007-1DC6-468F-9B86-3BBE0AD7CEC4",
                timestamp: "1602632967970",
                text: "Finished renaming /iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/folderwithanevenlongername to /iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/XXfolderwithanevenlongernameXX",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "share",
                paths: [
                    "/iplant/home/ipcdev/CORE-5257/subCORE-5257/test1/folderwithalongername/folderwithanevenlongername",
                ],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "1 file(s)/folder(s) have been shared with psarando",
            message: {
                id: "99CBAC33-AC0D-4747-BAA4-D7A7FAB6E9BE",
                timestamp: "1602632946037",
                text: "The following file(s)/folder(s) have been shared with psarando: folderwithanevenlongername",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "share",
                paths: ["/iplant/home/ipcdev/hello-shiny"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "1 file(s)/folder(s) have been shared with psarando",
            message: {
                id: "41F0F8EE-64F4-4064-AC5E-3DB04098BF71",
                timestamp: "1602632918654",
                text: "The following file(s)/folder(s) have been shared with psarando: hello-shiny",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "restore",
                paths: ["/iplant/home/ipcdev/lol"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished restoring 1 files(s)/folder(s) to their original locations",
            message: {
                id: "A01667DC-1A9C-4D17-976C-0158B9D12945",
                timestamp: "1602632844519",
                text: 'Finished restoring ["/iplant/trash/home/de-irods/ipcdev/lol.X1pKu1B"] to /iplant/home/ipcdev/lol',
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "move",
                paths: ["/iplant/home/ipcdev/logs"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished moving 1 file(s)/folder(s) to /iplant/home/ipcdev",
            message: {
                id: "AE62C0DF-2FC6-4EC7-9136-83823DBEE1C1",
                timestamp: "1602632806479",
                text: "Finished moving /iplant/home/ipcdev/test/logs to /iplant/home/ipcdev/logs",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "move",
                paths: ["/iplant/home/ipcdev/test/logs"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished moving 1 file(s)/folder(s) to /iplant/home/ipcdev/test",
            message: {
                id: "454B48E5-0E3B-49D1-9E2F-D004A0DB4300",
                timestamp: "1602632792551",
                text: "Finished moving /iplant/home/ipcdev/logs to /iplant/home/ipcdev/test/logs",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "trash",
                paths: ["/iplant/trash/home/de-irods/ipcdev/lol.X1pKu1B"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "Finished moving 1 files(s)/folder(s) to trash",
            message: {
                id: "87B01765-9B2B-4EC5-88F8-72911A280528",
                timestamp: "1602632774501",
                text: "Finished moving /iplant/home/ipcdev/lol to trash at /iplant/trash/home/de-irods/ipcdev/lol.X1pKu1B",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "rename",
                paths: ["/iplant/home/ipcdev/upload"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished renaming /iplant/home/ipcdev/upload.txt to upload",
            message: {
                id: "34D7EFA1-BB61-4B45-96F9-B08EED32978A",
                timestamp: "1602632738739",
                text: "Finished renaming /iplant/home/ipcdev/upload.txt to /iplant/home/ipcdev/upload",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "rename",
                paths: ["/iplant/home/ipcdev/upload.txt"],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject:
                "Finished renaming /iplant/home/ipcdev/upload to upload.txt",
            message: {
                id: "C0F33DF3-5715-4701-B722-FFA001966E21",
                timestamp: "1602632724716",
                text: "Finished renaming /iplant/home/ipcdev/upload to /iplant/home/ipcdev/upload.txt",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "share",
                paths: [
                    "/iplant/home/wregglej/logs/gitignore_global.txt",
                    "/iplant/home/wregglej/logs/recurisive_avu_queries.txt",
                    "/iplant/home/wregglej/logs/script-error.log",
                    "/iplant/home/wregglej/logs/script-output.log",
                ],
            },
            email_template: null,
            type: "data",
            seen: true,
            user: "ipcdev",
            subject: "wregglej has shared 4 file(s)/folder(s) with you.",
            message: {
                id: "D985EF47-2F4A-41F5-8D85-B8BF8CD7F46F",
                timestamp: "1602603884529",
                text: "wregglej has shared the following file(s)/folder(s) with you: gitignore_global.txt, recurisive_avu_queries.txt, script-error.log, script-output.log",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "share",
                analyses: [
                    {
                        analysis_id: "302b23a8-0cc1-11eb-82dc-62d47aced14b",
                        analysis_name: "DE_Word_Count_analysis1",
                        category_id: "",
                    },
                ],
            },
            email_template: null,
            type: "analysis",
            seen: true,
            user: "ipcdev",
            subject: "wregglej has shared 1 analysis with you.",
            message: {
                id: "A7235308-971C-4650-88E3-9CC650FE1D2F",
                timestamp: "1602603882538",
                text: "wregglej has shared the following analysis with you: DE_Word_Count_analysis1",
            },
        },
        {
            deleted: false,
            email: false,
            payload: {
                action: "share",
                apps: [
                    {
                        app_id: "4630cb28-63d7-11ea-a65b-008cfa5ae621",
                        app_name: "test-vbisque",
                        category_id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
                    },
                    {
                        app_id: "53e2679a-863d-11e4-adf2-236158ededce",
                        app_name: "testingcrap",
                        category_id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
                    },
                ],
            },
            email_template: null,
            type: "apps",
            seen: true,
            user: "ipcdev",
            subject: "wregglej has shared 2 apps with you.",
            message: {
                id: "B6051696-56D4-4D94-9ED6-BF55CC272EA7",
                timestamp: "1602603881415",
                text: "wregglej has shared the following apps with you: test-vbisque, testingcrap",
            },
        },
        {
            deleted: false,
            email: true,
            payload: {
                action: "added_to_team",
                email_address: "core-sw@iplantcollaborative.org",
                team_name: "sarahr:Blargh",
            },
            email_template: "added_to_team",
            type: "team",
            seen: true,
            user: "ipcdev",
            subject: "Added to team",
            message: {
                id: "31C9DE71-0BEF-4F98-BED3-70C9A6A9A812",
                timestamp: "1598914226732",
                text: "Added to team",
            },
        },
    ],
    "system-messages": [],
};
