export default {
    ADMIN_LIST: "admins",
    APP_LIST: "appList",
    BUTTONS: {
        DELETE_MI: "deleteMI",
        FOLLOW_BTN: "followBtn",
        FOLLOW_MI: "followMI",
        HELP_BTN: "helpBtn",
        SAVE_BTN: "saveBtn",
        UNFOLLOW_BTN: "unfollowBtn",
        UNFOLLOW_MI: "unfollowMI",
    },
    COMMUNITY_FILTER: "communityFilter",
    DELETE_COMMUNITY_DLG: "deleteCommunityDlg",
    DESCRIPTION: "description",
    DOT_MENU: "dotMenu",
    FOLLOW_COMMUNITY_DLG: "followCommunityDlg",
    HELP_DLG: "communityHelpDlg",
    NAME: "communityName",
    SUBJECT_SEARCH: "subjectSearch",
    TABLE: "table",
    TOOLBAR: "toolbar",
    UNFOLLOW_COMMUNITY_DLG: "unfollowCommunityDlg",
};
