export const myCommunityList = {
    groups: [
        {
            extension: "2testing",
            name: "flynn:2testing",
            type: "group",
            description: "desc2",
            id: "0572ce395953469d9550252093c553a1",
            display_name: "iplant:de:qa:teams:flynn:2testing",
            display_extension: "2testing",
            id_index: "13291",
        },
        {
            extension: "QA ",
            name: "flynn:QA ",
            type: "group",
            description: "p90 rrready",
            id: "bfcbc5c6beee4258ba77117c2a665be1",
            display_name: "iplant:de:qa:teams:flynn:QA ",
            display_extension: "QA ",
            id_index: "13273",
        },
        {
            extension: "graysonDick",
            name: "flynn:graysonDick",
            type: "group",
            description: "made by flynn",
            id: "33ccff8bca3e4c5db457322eb1e2b95d",
            display_name: "iplant:de:qa:teams:flynn:graysonDick",
            display_extension: "graysonDick",
            id_index: "13606",
        },
        {
            extension: "Dev Team",
            name: "ipcdev:Dev Team",
            type: "group",
            description: "testing a description",
            id: "c1fe2b741c5c40b78f178a29cebb8654",
            display_name: "iplant:de:qa:teams:ipcdev:Dev Team",
            display_extension: "Dev Team",
            id_index: "13206",
        },
        {
            extension: "testing",
            name: "jmittelmeier:testing",
            type: "group",
            description: "tesssttt",
            id: "4b08f86ddcdd494ca1cfd168c67f48df",
            display_name: "iplant:de:qa:teams:jmittelmeier:testing",
            display_extension: "testing",
            id_index: "12868",
        },
        {
            extension: "privateTeam",
            name: "qa-test1:privateTeam",
            type: "group",
            description: ", goodbye.",
            id: "a86baed6aa09418c88f23d63cd9b028a",
            display_name: "iplant:de:qa:teams:qa-test1:privateTeam",
            display_extension: "privateTeam",
            id_index: "13627",
        },
        {
            extension: "foo",
            name: "sarahr:foo",
            type: "group",
            description: "foo",
            id: "f6327365ade04edf8389bc43c30e6593",
            display_name: "iplant:de:qa:teams:sarahr:foo",
            display_extension: "foo",
            id_index: "11870",
        },
        {
            extension: "testing ad qw",
            name: "sonora_test:testing ad qw",
            type: "group",
            description: "edwe",
            id: "d66b67835778470ba234aaaa52441e98",
            display_name: "iplant:de:qa:teams:sonora_test:testing ad qw",
            display_extension: "testing ad qw",
            id_index: "13634",
        },
        {
            extension: "toddJason",
            name: "sonora_test:toddJason",
            type: "group",
            description: "f",
            id: "072aa869812247c48de9520964452807",
            display_name: "iplant:de:qa:teams:sonora_test:toddJason",
            display_extension: "toddJason",
            id_index: "13546",
        },
    ],
};
