export default {
    PARAM_TYPE: {
        DOUBLE: "Double",
        DOUBLE_SELECTION: "DoubleSelection",
        FILE_OUTPUT: "FileOutput",
        FLAG: "Flag",
        FOLDER_OUTPUT: "FolderOutput",
        INFO: "Info",
        INTEGER: "Integer",
        INTEGER_SELECTION: "IntegerSelection",
        MULTIFILE_OUTPUT: "MultiFileOutput",
        MULTILINE_TEXT: "MultiLineText",
        TEXT: "Text",
        TEXT_SELECTION: "TextSelection",
    },
    VALIDATOR_TYPE: {
        CHARACTER_LIMIT: "CharacterLimit",
        DOUBLE_ABOVE: "DoubleAbove",
        DOUBLE_BELOW: "DoubleBelow",
        DOUBLE_RANGE: "DoubleRange",
        INT_ABOVE: "IntAbove",
        INT_BELOW: "IntBelow",
        INT_RANGE: "IntRange",
        REGEX: "Regex",
    },
};
