export default {
    APP_LAUNCH_FORM: "templateForm",
    APP_LAUNCH_COMMENTS: "comments",
    APP_LAUNCH_DOUBLE_SELECTION: "doubleSelection",
    APP_LAUNCH_DOUBLE_SPINNER: "doubleSpinner",
    APP_LAUNCH_ENV_VAR: "envVar",
    APP_LAUNCH_FILE_SELECTOR: "fileSelector",
    APP_LAUNCH_FILE_FOLDER_INPUT: "inputFileFolder",
    APP_LAUNCH_FLAG: "flag",
    APP_LAUNCH_INFO_LABEL: "info",
    APP_LAUNCH_INPUT_FOLDER: "inputFolder",
    APP_LAUNCH_INTEGER_SELECTION: "integerSelection",
    APP_LAUNCH_INTEGER_SPINNER: "integerSpinner",
    APP_LAUNCH_MULTI_FILE_OUTPUT: "multiFileOutput",
    APP_LAUNCH_MULTI_LINE_TEXT: "multiLineText",
    APP_LAUNCH_NAME: "name",
    APP_LAUNCH_OUTPUT_FILE: "outputFile",
    APP_LAUNCH_OUTPUT_FOLDER: "outputFolder",
    APP_LAUNCH_REFERENCE_ANNOTATION: "referenceAnnotation",
    APP_LAUNCH_REFERENCE_GENOME: "referenceGenome",
    APP_LAUNCH_REFERENCE_SEQUENCE: "referenceSequence",
    APP_LAUNCH_RESOURCE_REQUESTS: "resourceRequests",
    APP_LAUNCH_RETAIN_INPUTS: "retainInputs",
    APP_LAUNCH_REVIEW: "launchAnalysisReview",
    APP_LAUNCH_TEXT_INPUT: "textInput",
    APP_LAUNCH_TEXT_SELECTION: "textSelection",
    BUTTONS: {
        EXPAND: "expand",
        SUBMIT: "submit",
        STEP: "stepButton",
        STEP_BACK: "stepBackButton",
        STEP_NEXT: "stepNextButton",
    },
    LAUNCH_ANALYSIS_GROUP: "launchAnalysisGroup",
    RESOURCE_REQUESTS: {
        TOOL_CPU: "idToolCpu",
        TOOL_MEM: "idToolMem",
        MIN_DISK_SPACE: "minDiskSpace",
    },
    TEMPLATE_GROUP: "group",
};
