const ids = {
    BASE: "instantlaunches",
    LIST: "list",
    MAPPING: "mapping",
    SAVED_LAUNCHES: "savedLaunches",
    CREATE: "create",
    DIALOG: "dialog",
    CLOSE: "close",
    BUTTON: "button",
    TITLE: "title",
    SKELETON: "skeleton",
    ADD: "add",
    TABLE: "table",
    ROW: "row",
    ADDED_BY: "addedBy",
    ADDED_ON: "addedOn",
    DASH: "dashboard",
    ADD_DASH: "addToDashboard",
    RM_DASH: "removeFromDashboard",
    DELETE: "delete",
    NAME: "name",
    PATTERN: "pattern",
    KIND: "kind",
    FORM: "form",
    MENU: "menu",
    GLOB: "glob",
    INFO_TYPE: "infoType",
    EDITOR: "editor",
    CREATOR: "creator",
    SUBMISSION: "submission",
    PROGRESS: "progress",
    LAUNCH: "launch",
    NAV_DRAWER: "navDrawer",
    RM_DRAWER: "removeFromDrawer",
    LISTING: "listing",
    ADD_LISTING: "addToListing",
    RM_LISTING: "removeFromListing",
    ADD_NAV_DRAWER: "addToDrawer",
    ACCESS_REQUEST_DLG: "accessRequestDlg",
    RUN_ERROR_DLG: "runErrorDlg",
};

export default ids;
