export default {
    PARAM_TYPE: {
        DOUBLE: "Double",
        DOUBLE_SELECTION: "DoubleSelection",
        ENV_VAR: "EnvironmentVariable",
        FILE_FOLDER_INPUT: "FileFolderInput",
        FILE_INPUT: "FileInput",
        FILE_OUTPUT: "FileOutput",
        FLAG: "Flag",
        FOLDER_INPUT: "FolderInput",
        FOLDER_OUTPUT: "FolderOutput",
        INFO: "Info",
        INPUT: "Input",
        INTEGER: "Integer",
        INTEGER_SELECTION: "IntegerSelection",
        MULTIFILE_OUTPUT: "MultiFileOutput",
        MULTIFILE_SELECTOR: "MultiFileSelector",
        MULTILINE_TEXT: "MultiLineText",
        NUMBER: "Number",
        OUTPUT: "Output",
        REFERENCE_ANNOTATION: "ReferenceAnnotation",
        REFERENCE_GENOME: "ReferenceGenome",
        REFERENCE_SEQUENCE: "ReferenceSequence",
        SELECTION: "Selection",
        TEXT: "Text",
        TEXT_SELECTION: "TextSelection",
        TREE_SELECTION: "TreeSelection",
        VALUE_SELECTION: "ValueSelection",
    },
};
