export default {
    BASE: "vice.admin.filter",
    ROOT: "root",
    DEPLOYMENT: "deployment",
    SERVICE: "service",
    CONFIGMAPS: "configmaps",
    INGRESS: "ingress",
    PODS: "pods",
    DEPLOYMENT_FIELD_SELECT: "deploymentFieldSelect",
    SERVICE_FIELD_SELECT: "serviceFieldSelect",
    POD_FIELD_SELECT: "podFieldSelect",
    CONFIGMAP_FIELD_SELECT: "configmapFieldSelect",
    INGRESS_FIELD_SELECT: "ingressFieldSelect",
    ANALYSIS_FIELD_SELECT: "analysisFieldSelect",
};
