import React from "react";
import fetchMock from "fetch-mock";
import { UploadTrackingProvider } from "../../src/contexts/uploadTracking";
import Listing from "../../src/components/apps/listing/Listing";

export default {
    title: "Apps",
};

function ListingTest(props) {
    const logger = (message) => {
        console.log(message);
    };

    return (
        <UploadTrackingProvider>
            <Listing baseId="tableView" />
        </UploadTrackingProvider>
    );
}

const successResp = {
    total: 643,
    apps: [
        {
            integration_date: "2016-01-22T00:24:54.000Z",
            description: "16sblaster",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: true,
            integrator_name: "Ken Youensclark",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "16sblaster",
            system_id: "de",
            is_public: true,
            id: "13ad5f48-bfb4-11e5-a5df-4b1d67d0fef0",
            edited_date: "2017-02-07T20:15:30.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "kyclark@email.arizona.edu",
            app_type: "DE",
            rating: { average: 5.0, total: 1 },
        },
        {
            integration_date: "2020-01-07T18:48:45.000Z",
            description:
                "The is dev version 3.0 for the GEA Leptin RNA-Seq lab. This Jupyter lab VICE application will import data from NCBI SRA, and provides notebooks for QC and trimming of the data, pseudoalignment with Kallisto, and visualization. ",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason:
                    "Job type, interactive, can't currently be included in a pipeline.",
            },
            is_favorite: false,
            integrator_name: "williams",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "3.1 dev GEA Leptin RNA Seq Lab",
            system_id: "de",
            is_public: true,
            id: "2b9d31fe-3162-11ea-a78a-008cfa5ae621",
            edited_date: "2020-01-07T18:48:45.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "williams@cshl.edu",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2016-02-18T16:33:29.000Z",
            description:
                "Assembles pseudomolecules representing high-copy number repeats from genomic sample sequence data.  AAARF is intended for use with small, random, sample sequence datasets, not large NGS datasets.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Jeremy Debarry",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "AAARFv1.0.1",
            system_id: "de",
            is_public: true,
            id: "bf750284-d659-11e5-9346-eb45ddf114f9",
            edited_date: "2016-11-23T18:01:47.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "jdebarry@email.arizona.edu",
            app_type: "DE",
            rating: { average: 4.5, total: 4 },
        },
        {
            integration_date: "2014-10-10T10:45:35.000Z",
            description:
                "For use in mutant identification pipeline to label MUTANT PARENT file before concatenation i.e. adds label column to file",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Laura Gardiner",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "add column to file",
            system_id: "de",
            is_public: true,
            id: "0f1b6b9a-bb92-4ef1-ae73-344fd35ae82f",
            edited_date: "2014-04-15T06:24:27.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "lgardine@liv.ac.uk",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/add+column+to+file",
            rating: { average: 5.0, total: 2 },
        },
        {
            integration_date: "2014-10-10T12:05:34.000Z",
            description:
                "For use in mutant identification pipeline to label MUTANT BULK file before concatenation i.e. adds label column to file",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Laura Gardiner",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "add column to file2",
            system_id: "de",
            is_public: true,
            id: "5707bdf5-67f6-4c18-a0d6-5986fa019681",
            edited_date: "2016-11-23T17:44:28.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "lgardine@liv.ac.uk",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/add+column+to+file2",
            rating: { average: 5.0, total: 1 },
        },
        {
            integration_date: "2013-04-24T17:51:38.000Z",
            description:
                "Admixture is a software tool for maximum likelihood estimation of individual ancestries from multilocus SNP genotype datasets.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Liya Wang",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Admixture",
            system_id: "de",
            is_public: true,
            id: "6768773a-854a-11e4-9c72-7fd0f0b43075",
            edited_date: "2013-04-22T14:57:56.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "wangli@cshl.edu",
            app_type: "DE",
            wiki_url:
                "http://pods.iplantcollaborative.org/wiki/display/DEapps/Admixture",
            rating: { average: 1.0, total: 1 },
        },
        {
            integration_date: "2020-03-02T15:36:48.000Z",
            description: "Performs ALLMAPS merge and path",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason:
                    "Analysis, 58f783bc-5c95-11ea-b10d-008cfa5ae621, has too many steps for a pipeline.",
            },
            is_favorite: false,
            integrator_name: "Amanda Cooksey",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "ALLMAPS",
            system_id: "de",
            is_public: true,
            id: "58f783bc-5c95-11ea-b10d-008cfa5ae621",
            edited_date: "2020-03-02T15:36:48.000Z",
            step_count: 2,
            can_run: true,
            integrator_email: "amcooksey@email.arizona.edu",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2020-03-02T15:33:49.000Z",
            description:
                "ALLMAPS orders scaffolds by maximizing colinearity to a collection of genetic/genomic maps into the final chromosome build.  This is step one: merging maps into a bed file and generating the weights file. http://goo.gl/KI61Ow",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Amanda Cooksey",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "ALLMAPS merge",
            system_id: "de",
            is_public: true,
            id: "6ff82cda-5c98-11ea-aad3-008cfa5ae621",
            edited_date: "2020-03-02T15:33:49.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "amcooksey@email.arizona.edu",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2020-01-21T16:53:05.000Z",
            description:
                "ALLMAPS orders scaffolds by maximizing colinearity to a collection of genetic/genomic maps into the final chromosome build.  This is step two: using the merged maps and weight files to generate the map. http://goo.gl/KI61Ow",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Amanda Cooksey",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "ALLMAPS path",
            system_id: "de",
            is_public: true,
            id: "0adf9b82-3c66-11ea-9a20-008cfa5ae621",
            edited_date: "2020-01-21T16:53:05.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "amcooksey@email.arizona.edu",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2013-05-24T21:44:49.000Z",
            description:
                "This App will add existing reference annotation information to newly assembled transcripts in GFF format.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: true,
            integrator_name: "Roger Barthelson",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Annotate transcripts",
            system_id: "de",
            is_public: true,
            id: "676846d4-854a-11e4-980d-7f0fcca75dbb",
            edited_date: "2013-05-24T20:56:03.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "rogerab@email.arizona.edu",
            app_type: "DE",
            wiki_url:
                "http://pods.iplantcollaborative.org/wiki/display/DEapps/Annotate+transcripts",
            rating: { average: 1.0, total: 1 },
        },
        {
            integration_date: "2013-07-08T03:27:47.000Z",
            description:
                "AntEpiSeeker, a 2-stage ant colony optimization alg. that is a powerful and efficient tool for detecting epistasis in case-control design.  Limitations - a phenotype that must be binary and genotypes must be heterozygous with only two heritability traits.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Kurt Michels",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "AntEpiSeeker 2.0",
            system_id: "de",
            is_public: true,
            id: "e328b780-49e4-4421-ac2e-12b49504bcd2",
            edited_date: "2013-07-08T03:16:50.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "kamichels@math.arizona.edu",
            app_type: "DE",
            wiki_url:
                "http://pods.iplantcollaborative.org/wiki/display/DEapps/AntEpiSeeker+2.0",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2019-12-11T17:42:46.000Z",
            description:
                "A utility to add unclustered sequences to OrthoMCL output.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Amanda Cooksey",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "appendUnclustered",
            system_id: "de",
            is_public: true,
            id: "e0937512-1535-11ea-b8be-008cfa5ae621",
            edited_date: "2019-12-11T17:42:46.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "amcooksey@email.arizona.edu",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2017-02-03T19:45:33.000Z",
            description:
                "Conservation Module of the APPLES package\nhttps://github.com/cyversewarwick/apples",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Uk Cyverse",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "APPLES_conservation",
            system_id: "de",
            is_public: true,
            id: "d99ca952-dbe2-11e6-9e37-0242ac120003",
            edited_date: "2017-02-03T19:45:33.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "admin@cyverse.warwick.ac.uk",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2017-03-15T19:50:02.000Z",
            description:
                "The APPLES (Analysis of Plant Promoter-Linked Elements) software package is a set of tools to analyse promoter sequences on a genome-wide scale. The RBH tool is part of the APPLES package which searches for orthologous as Reciprocal Best Hits (RBH).",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Uk Cyverse",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "APPLES_rbh",
            system_id: "de",
            is_public: true,
            id: "99df0c66-dce5-11e6-a30f-0242ac120003",
            edited_date: "2017-03-15T19:50:02.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "admin@cyverse.warwick.ac.uk",
            app_type: "DE",
            rating: { average: 2.0, total: 2 },
        },
        {
            integration_date: "2014-07-17T20:53:29.000Z",
            description:
                "Determines a series of metrics to help evaluate a genome assembly. From the Assemblathon.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Roger Barthelson",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Assembly Stats (assemblathon tool)",
            system_id: "de",
            is_public: true,
            id: "21d1eee5-364f-4384-b00b-c19fcd2ca488",
            edited_date: "2014-07-15T21:00:28.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "rogerab@email.arizona.edu",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/Assembly+Stats+%28assemblathon+tool%29",
            rating: { average: 3.6666666666666665, total: 3 },
        },
        {
            integration_date: "2012-02-29T22:00:45.000Z",
            description:
                "This app from the Plantagora project produces a list of metrics on a genome assembly by aligning it against a genome reference sequence that the user chooses.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Roger Barthelson",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Assess Assembly vs whole genome",
            system_id: "de",
            is_public: true,
            id: "ec009883-b5c5-4605-9d78-17dcab530184",
            edited_date: "2012-02-29T22:00:38.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "rogerab@email.arizona.edu",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/Assess+Assembly+vs+whole+genome",
            rating: { average: 4.0, total: 2 },
        },
        {
            description: "A simple demo app",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "sriram",
            beta: false,
            permission: "own",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Austria Demo",
            system_id: "de",
            is_public: false,
            id: "5b52c412-6b8e-11e9-81f7-008cfa5ae621",
            edited_date: "2019-09-04T13:46:32.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "sriram@iplantcollaborative.org",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            description: "demo",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason:
                    "Analysis, dab9d998-6b8e-11e9-b782-008cfa5ae621, has too many steps for a pipeline.",
            },
            is_favorite: false,
            integrator_name: "sriram",
            beta: false,
            permission: "own",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "austria-wf",
            system_id: "de",
            is_public: false,
            id: "dab9d998-6b8e-11e9-b782-008cfa5ae621",
            edited_date: "2019-04-30T21:28:11.000Z",
            step_count: 2,
            can_run: true,
            integrator_email: "sriram@iplantcollaborative.org",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2018-05-31T15:03:50.000Z",
            description:
                "Ballgown R package RNA seq differential expression analysis",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Kapeel Chougule",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Ballgown",
            system_id: "de",
            is_public: true,
            id: "685a0588-64de-11e8-af6e-008cfa5ae621",
            edited_date: "2018-05-31T15:03:50.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "kchougul@cshl.edu",
            app_type: "DE",
            rating: { average: 5.0, total: 3 },
        },
        {
            integration_date: "2019-08-19T21:37:23.000Z",
            description:
                "Ballgown R package RNA seq differential expression analysis",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Upendra Kumar Devisetty",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Ballgown-2.0",
            system_id: "de",
            is_public: true,
            id: "ed197e38-6d9a-11e8-91a1-008cfa5ae621",
            edited_date: "2019-10-16T21:46:40.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "upendra@cyverse.org",
            app_type: "DE",
            rating: { average: 5.0, total: 1 },
        },
        {
            integration_date: "2013-03-19T19:23:20.000Z",
            description:
                "Enter a bam file and a matching annotation file and get counts for transcripts or genes",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Roger Barthelson",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Bam to Counts (general)",
            system_id: "de",
            is_public: true,
            id: "51000872-1c9b-4d1a-b582-e46926c98aa3",
            edited_date: "2013-03-19T17:10:36.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "rogerab@email.arizona.edu",
            app_type: "DE",
            wiki_url:
                "http://pods.iplantcollaborative.org/wiki/display/DEapps/Bam+to+Counts+%28general%29",
            rating: { average: 3.5, total: 2 },
        },
        {
            description:
                "From a BAM file of aligned RNAseq reads, generates a tab-delimited count file for each gene. Assumes input of a non-redundant exon annotation file. Allows user to specify an output file name.",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason:
                    "Analysis, 581dfdf9-653f-4db7-8fb2-d64438fbddf1, has too many steps for a pipeline.",
            },
            is_favorite: false,
            integrator_name: "Matthew Vaughn",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "BAM to Counts (named outputs)",
            system_id: "de",
            is_public: true,
            id: "581dfdf9-653f-4db7-8fb2-d64438fbddf1",
            step_count: 2,
            can_run: true,
            integrator_email: "vaughn@tacc.utexas.edu",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/RNAseq",
            rating: { average: 0.0, total: 0 },
        },
        {
            integration_date: "2015-04-29T21:05:13.000Z",
            description: "Extract unmappled reads from a BAM file\n",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Dongliang Wu",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "bam2fastq_unmapped",
            system_id: "de",
            is_public: true,
            id: "f2c26674-c460-11e4-af99-3b9dd34014f8",
            edited_date: "2015-04-29T21:05:13.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "dw358@hawaii.edu",
            app_type: "DE",
            rating: { average: 5.0, total: 1 },
        },
        {
            description:
                "A robust model-based biclustering method that can discover biologically significant gene-condition clusters in microarray data.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Elijah Meyers",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Bayesian BiClustering",
            system_id: "de",
            is_public: true,
            id: "cca286bd-3471-879b-7298-d79751635482",
            step_count: 1,
            can_run: true,
            integrator_email: "esm2310@vt.edu",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/Bayesian%20BiClustering",
            rating: { average: 3.0, total: 3 },
        },
        {
            integration_date: "2018-07-26T21:38:04.000Z",
            description: "SNP/indel variant calling from VCF/BCF.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "Amanda Cooksey",
            beta: true,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "BCFtools 1.8 call",
            system_id: "de",
            is_public: true,
            id: "17434bb4-9058-11e8-87dd-008cfa5ae621",
            edited_date: "2018-07-26T21:38:04.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "amcooksey@email.arizona.edu",
            app_type: "DE",
            rating: { average: 0.0, total: 0 },
        },
    ],
};

export const AppsListingTest = () => {
    fetchMock.get(/\/api\/apps.*/, successResp);
    return <ListingTest />;
};
