export default {
    TEAMS: {
        ALL_TEAMS_MI: "allTeamsMI",
        BASE: "teams",
        CHECKBOX: "checkbox",
        DOT_MENU: "dotMenu",
        HELP_DLG: "teamHelpDlg",
        MY_TEAMS_MI: "myTeamsMI",
        LINK: "link",
        TOOLBAR: "toolbar",
        TEAM_FILTER: "teamFilter",
        SEARCH: "searchField",
        TABLE: "table",
    },
    EDIT_TEAM: {
        NAME: "name",
        DESCRIPTION: "description",
        ADMIN: "admin",
        READ: "read",
        VIEW: "view",
        PUBLIC_PRIVILEGES: "publicPrivileges",
        MEMBERS: "members",
        PRIVILEGE: "privilege",
        HELP_POPOVER: "helpMessage",
    },
    BUTTONS: {
        CREATE_BTN: "createBtn",
        CREATE_MI: "createMI",
        DELETE: "deleteBtn",
        HELP_BTN: "helpBtn",
        HELP_MI: "helpMI",
    },
};
