export default {
    ACCOUNT_BTN: "accountButton",
    ACCOUNT_MI: "accountMenuItem",
    ADMIN_MI: "adminMenuItem",
    ANALYSES_BTN: "analysesButton",
    ANALYSES_MI: "analysesMenuItem",
    APPS_BTN: "appsButton",
    APPS_MI: "appsMenuItem",
    APP_BAR_BASE: "appBar",
    DASHBOARD_BTN: "dashboardButton",
    DASHBOARD_MI: "dashboardMenuItem",
    DATA_BTN: "dataButton",
    DATA_MI: "dataMenuItem",
    DRAWER_MENU: "drawerMenu",
    DRAWER_MENU_BTN: "drawerMenuButton",
    INTERCOM_WIDGET: "cyverse_intercom_support",
    MORE_BTN: "moreButton",
    MORE_MI: "moreMenuItem",
    NAVIGATION: "navigation",
    NOTIFICATION_BTN: "notificationButton",
    REF_GENOME_MI: "referenceGenomeMenuItem",
    SEARCH_BTN: "searchButton",
    SEARCH_MI: "searchMenuItem",
    SETTINGS_MI: "settingsMenuItem",
    USER_MENU_BTN: "userMenuButton",
    VICE_MI: "viceMenuItem",
};
