export default {
    APP_BAR_BASE: "appBar",
    ACCOUNT_BTN: "accountButton",
    AVATAR_BTN: "avatarButton",
    NOTIFICATION_BTN: "notificationButton",
    SEARCH_BTN: "searchButton",
    DRAWER_MENU_BTN: "drawerMenuButton",
    DRAWER_MENU: "drawerMenu",
    USER_MENU_BTN: "userMenuButton",
    DASHBOARD_BTN: "dashboardButton",
    APPS_BTN: "appsButton",
    DATA_BTN: "dataButton",
    ANALYSES_BTN: "analysesButton",
    MORE_BTN: "moreButton",
    NAVIGATION: "navigation",
    ACCOUNT_MI: "accountMenuItem",
    DASHBOARD_MI: "dashboardMenuItem",
    APPS_MI: "appsMenuItem",
    DATA_MI: "dataMenuItem",
    ANALYSES_MI: "analysesMenuItem",
    MORE_MI: "moreMenuItem",
    SEARCH_MI: "searchMenuItem",
    SETTINGS_MI: "settingsMenuItem",
    INTERCOM_WIDGET: "cyverse_intercom_support",
};
