export default {
    FROM_DATE: "fromDate",
    FILE_SIZE_GREATER_VAL: "fileSizeGreaterVal",
    TO_DATE: "toDate",
    FILE_NAME: "fileName",
    FILE_SIZE_GREATER_UNIT: "fileSizeGreaterUnit",
    FILE_SIZE_LESS_THAN_VAL: "fileSizeLessThanVal",
    FILE_SIZE_LESS_THAN_UNIT: "fileSizeLessThanUnit",
    METADATA_ATTRIBUTE: "metadataAttribute",
    METADATA_VALUE: "metadataValue",
    PATH_PREFIX: "pathPrefix",
    TAG_SEARCH: "tagSearch",
    SEARCH_FORM: "searchForm",
    ADVANCED_SEARCH_DLG: "advancedSearchDlg",
    MODIFIED: "modified",
    CREATED: "created",
    OWNER: "owner",
    PERMISSION_VALUE: "permissionValue",
    PERMISSION_USER_SEARCH: "permissionUserSearch",
    USER_PANEL: "userPanel",
    ADVANCED_SEARCH_BTN: "advancedSearchBtn",
};
