const ids = {
    CHECKBOX: "checkbox",
    IMAGE_NAME: "image-name",
    INSTALLED_TOOLS_DLG: "installedToolsDlg",
    LISTING_TABLE: "listing-table",
    NAME: "name",
    STATUS: "status",
    TAG: "tag",
    DETAILS_DRAWER: "detailsDrawer",
    INFO_TAB: "infoTab",
    APPS_USING_TOOL: "appsUsingTool",

    EDIT_TOOL_DLG: {
        NAME: "name",
        DESCRIPTION: "toolDesc",
        VERSION: "toolVersion",
        ATTRIBUTION: "attribution",
        LOCATION: "location",
        IMAGE_NAME: "imageName",
        DOCKER_URL: "url",
        TYPE: "type",
        OSG_IMAGE_PATH: "osgImagePath",
        ENTRYPOINT: "entrypoint",
        WORKING_DIR: "workingDirectory",
        CONTAINER_UID: "uid",
        MAX_CPU_CORES: "maxCPUCores",
        MEMORY_LIMIT: "memoryLimit",
        MIN_DISK_SPACE: "minDiskSpace",
        CONTAINER_PORTS: "containerPorts",
        PIDS_LIMIT: "pidsLimit",
        RESTRICTED: "restricted",
        NETWORK_MODE: "networkMode",
        TIME_LIMIT: "timeLimit",
        IMPLEMENTOR: "implementor",
        IMPLEMENTOR_EMAIL: "implementorEmail",
        SAMPLE_INPUT_FILES: "sampleInputFiles",
        SAMPLE_OUTPUT_FILES: "sampleOutputFiles",
        CONTAINER_IMAGE: "containerImage",
        TAG: "tag",
        INTERACTIVE: "interactive",
        CONTAINER_NAME: "containerName",
        MIN_MEMORY_LIMIT: "minMemoryLimit",
        CPU_SHARES: "cpuShares",
        MIN_CPU_CORES: "minCPUCores",
        SKIP_TMP_MOUNT: "skipTmpMount",
        CONTAINER_DEVICES: "containerDevices",
        CONTAINER_VOLUMES: "containerVolumes",
        CONTAINER_PORT: "containerPort",
        HOST_PATH: "hostPath",
        CONTAINER_PATH: "containerPath",
        NAME_PREFIX: "namePrefix",
        READ_ONLY: "readOnly",
        TOOL_IMPLEMENTATION: "toolImplementation",
        RESTRICTIONS: "restrictions",
        HOST_PORT: "hostPort",
        BIND_TO_HOST: "bindToHost",
        OVERWRITE_TOOL_DLG: "overWriteDialog",
    },

    BUTTONS: {
        SAVE: "saveBtn",
        CANCEL: "cancelBtn",
        ADD: "addBtn",
        DELETE: "deleteBtn",
        SUBMIT: "submitBtn",
        OK: "okBtn",
    },

    PORTS_TABLE: {
        NAME: "name",
        DELETE: "remove",
    },

    DEVICES_TABLE: {
        HOST_PATH: "hostPath",
        CONTAINER_PATH: "containerPath",
    },

    MANAGE_TOOLS: {
        VIEW: "toolsView",
        TOOLBAR: "toolbar",
        TOOLS_MENU: "toolsMenu",
        SHARE: "share",
        SEARCH: "search",
        TOOL_FILTER: "toolFilter",
        ALL_MI: "all",
        MY_TOOLS_MI: "myTools",
        PUBLIC_MI: "public",
        REFRESH: "refresh",
        ADD_TOOL_MI: "addTools",
        REQUEST_TOOL_MI: "newToolRequest",
        EDIT_TOOL_MI: "editTool",
        FILTER_TOOLS_MI: "filterTools",
        DELETE_TOOL_MI: "deleteTool",
        USE_IN_APP_MI: "useInApps",
        SHARE_MI: "shareCollabs",
        MAKE_PUBLIC_MI: "sharePublic",
        TOOL_INFO_BTN: "toolInfoCell",
        TOOL_INFO_MI: "toolInfo",
        TOOL_CHECKBOX: "checkBox",
        VIEW_FILTER_FIELD: "filterField",
    },

    TOOL_REQUEST: {
        ADMIN_TOOL_REQUEST_DETAILS: "adminToolRequestDetailsDlg",
        DIALOG: "toolRequestDlg",
        NAME: "name",
        DESCRIPTION: "description",
        SRC_LINK: "srcLink",
        COMMAND_LINE: "commandLine",
        VERSION: "version",
        DOCUMENTATION: "documentation",
        INSTRUCTIONS: "instructions",
        TEST_DATA_LINK: "testDataLink",
        REQUESTED_BY: "requestedBy",
        DATE_SUBMITTED: "dateSubmitted",
        LAST_UPDATED: "lastUpdated",
        STATUS: "status",
    },
};

export default ids;
