export const dataSearchResp = {
    total: 11149,
    max_score: null,
    hits: [
        {
            matched_queries: null,
            _id: "f5126568-7cd0-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-12-15-18-45.2",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586704749000,
                label: "DE_Word_Count_analysis1-2020-04-12-15-18-45.2",
                id: "f5126568-7cd0-11ea-a8b6-fa163e806578",
                dateCreated: 1586704749000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "b0a08921-13ec-4ce2-bf31-e3f1fd5e9b4c",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-12-15-18-45.2"],
        },
        {
            matched_queries: null,
            _id: "f05ff7fa-7cd1-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-12-15-25-42.2",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586705171000,
                label: "DE_Word_Count_analysis1-2020-04-12-15-25-42.2",
                id: "f05ff7fa-7cd1-11ea-a8b6-fa163e806578",
                dateCreated: 1586705171000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "269735e7-b92b-4fa5-ae82-069718be08ab",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-12-15-25-42.2"],
        },
        {
            matched_queries: null,
            _id: "cba1cbcc-7d54-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-07-02-21.4",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586761373000,
                label: "DE_Word_Count_analysis1-2020-04-13-07-02-21.4",
                id: "cba1cbcc-7d54-11ea-a8b6-fa163e806578",
                dateCreated: 1586761373000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "592550f0-d59b-40f2-aae2-c55e210b7d11",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-07-02-21.4"],
        },
        {
            matched_queries: null,
            _id: "039a5d1c-7d57-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-07-18-10.2",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586762326000,
                label: "DE_Word_Count_analysis1-2020-04-13-07-18-10.2",
                id: "039a5d1c-7d57-11ea-a8b6-fa163e806578",
                dateCreated: 1586762326000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "c6001319-e0da-4558-996c-608654f295bf",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-07-18-10.2"],
        },
        {
            matched_queries: null,
            _id: "e7874742-7d57-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-07-24-33.8",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586762708000,
                label: "DE_Word_Count_analysis1-2020-04-13-07-24-33.8",
                id: "e7874742-7d57-11ea-a8b6-fa163e806578",
                dateCreated: 1586762708000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "8e4166c2-03b9-406f-ab5c-ad800b026058",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-07-24-33.8"],
        },
        {
            matched_queries: null,
            _id: "90e89f34-7d58-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-07-29-23.5",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586762992000,
                label: "DE_Word_Count_analysis1-2020-04-13-07-29-23.5",
                id: "90e89f34-7d58-11ea-a8b6-fa163e806578",
                dateCreated: 1586762992000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "7053aa7d-e4d1-4c64-9bcc-1b2ee2a95496",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-07-29-23.5"],
        },
        {
            matched_queries: null,
            _id: "8b21a174-7d60-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-08-26-24.8",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586766419000,
                label: "DE_Word_Count_analysis1-2020-04-13-08-26-24.8",
                id: "8b21a174-7d60-11ea-a8b6-fa163e806578",
                dateCreated: 1586766419000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "8cfb6194-e725-4b5d-8c94-8495fa66e85e",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-08-26-24.8"],
        },
        {
            matched_queries: null,
            _id: "a62d616c-7d7c-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-11-47-37.2",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586778490000,
                label: "DE_Word_Count_analysis1-2020-04-13-11-47-37.2",
                id: "a62d616c-7d7c-11ea-a8b6-fa163e806578",
                dateCreated: 1586778490000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "9237fe06-d326-4624-920c-7d02e2e4274b",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-11-47-37.2"],
        },
        {
            matched_queries: null,
            _id: "77bba46e-7d8c-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-13-40-49.2",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586785284000,
                label: "DE_Word_Count_analysis1-2020-04-13-13-40-49.2",
                id: "77bba46e-7d8c-11ea-a8b6-fa163e806578",
                dateCreated: 1586785284000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "56f201e0-e936-44bb-be15-6b932b6cad9a",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-13-40-49.2"],
        },
        {
            matched_queries: null,
            _id: "7ea579ce-7d8e-11ea-a8b6-fa163e806578",
            _explanation: null,
            _routing: "",
            highlight: null,
            fields: { permission: ["own"] },
            _type: "folder",
            _parent: "",
            _score: null,
            _index: "data-qa_write",
            inner_hits: null,
            _version: null,
            _source: {
                userPermissions: [
                    { user: "rodsadmin#iplant", permission: "own" },
                    { user: "sriram#iplant", permission: "own" },
                ],
                path: "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-13-55-34.2",
                fileSize: 0,
                creator: "sriram#iplant",
                fileType: "",
                dateModified: 1586786155000,
                label: "DE_Word_Count_analysis1-2020-04-13-13-55-34.2",
                id: "7ea579ce-7d8e-11ea-a8b6-fa163e806578",
                dateCreated: 1586786155000,
                metadata: [
                    {
                        attribute: "ipc-analysis-id",
                        value: "67d15627-22c5-42bd-8daf-9af5deecceab",
                        unit: "UUID",
                    },
                    {
                        attribute: "ipc-execution-id",
                        value: "c24847a7-a1c9-4aa0-bc79-d56d3d4fc8f4",
                        unit: "UUID",
                    },
                ],
            },
            _uid: "",
            sort: ["DE_Word_Count_analysis1-2020-04-13-13-55-34.2"],
        },
    ],
};
export const appsSearchResp = {
    total: 10,
    apps: [
        {
            integration_date: "2015-08-04T16:30:16.000Z",
            description: "Counts the number of words in a file",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: true,
            integrator_name: "Default DE Tools",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "DE Word Count",
            system_id: "de",
            overall_job_type: "executable",
            is_public: true,
            id: "67d15627-22c5-42bd-8daf-9af5deecceab",
            edited_date: "2020-03-10T01:24:22.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "support@iplantcollaborative.org",
            app_type: "DE",
            wiki_url: "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
            rating: {
                average: 3.6666666666666665,
                total: 3,
                user: 4,
                comment_id: 0,
            },
        },
        {
            integration_date: "2017-07-22T00:43:06.000Z",
            description:
                "Parses a large HT Path List file from the Discovery Environment into smaller HT Path List files, in batches of 128 paths per output file.",
            deleted: false,
            pipeline_eligibility: { is_valid: true, reason: "" },
            is_favorite: false,
            integrator_name: "psarando",
            beta: true,
            permission: "read",
            isBlessed: false,
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Large HT Path List splitter",
            limitChecks: { canRun: true, results: [] },
            system_id: "de",
            overall_job_type: "executable",
            is_public: false,
            id: "8bc4be4e-6e69-11e7-8a93-008cfa5ae621",
            edited_date: "2021-06-23T00:52:46.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "psarando@iplantcollaborative.org",
            app_type: "DE",
            rating: { average: 0, total: 0 },
        },
        {
            description: "osgwc",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason: "Job type, osg, can't currently be included in a pipeline.",
            },
            is_favorite: false,
            integrator_name: "Sarah Roberts",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "osgwc",
            system_id: "de",
            overall_job_type: "osg",
            is_public: false,
            id: "29e19882-5d1f-11e8-a92d-5a03816fc427",
            edited_date: "2018-08-16T17:50:47.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "sarah.cyverse@gmail.com",
            app_type: "DE",
            rating: { average: 0, total: 0 },
        },
        {
            description: "osgwc-sf",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason: "Job type, osg, can't currently be included in a pipeline.",
            },
            is_favorite: false,
            integrator_name: "Sarah Roberts",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "osgwc-sf",
            system_id: "de",
            overall_job_type: "osg",
            is_public: false,
            id: "69a4ab98-5d25-11e8-b21e-5a03816fc427",
            edited_date: "2018-08-16T17:50:52.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "sarah.cyverse@gmail.com",
            app_type: "DE",
            rating: { average: 0, total: 0 },
        },
        {
            description:
                'Interactive access to StarView in a Windows environment. Use "user" and "password" to login to the initial page.',
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason: "Job type, interactive, can't currently be included in a pipeline.",
            },
            is_favorite: false,
            integrator_name: "Edwin Skidmore",
            beta: false,
            permission: "read",
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "SquidStarView",
            system_id: "de",
            overall_job_type: "interactive",
            is_public: false,
            id: "b9d6cd2e-cea0-11e9-81ff-008cfa5ae621",
            edited_date: "2020-03-05T22:09:32.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "edwin@cyverse.org",
            app_type: "DE",
            rating: { average: 0, total: 0 },
        },
        {
            integration_date: "2020-11-17T12:23:15.000Z",
            description:
                "This workflow does mapping using bowtie2 and converts bowtie2 output to sorted and indexed binary files.\n",
            deleted: false,
            pipeline_eligibility: {
                is_valid: false,
                reason: "Analysis, 33152660-1480-11eb-9ec7-008cfa5ae621, has too many steps for a pipeline.",
            },
            is_favorite: false,
            integrator_name: "REETU TUTEJA",
            beta: true,
            permission: "read",
            isBlessed: false,
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Bowtie2-Map-SortBam Workflow",
            limitChecks: {
                canRun: true,
                results: [],
            },
            system_id: "de",
            overall_job_type: "executable",
            is_public: true,
            id: "33152660-1480-11eb-9ec7-008cfa5ae621",
            edited_date: "2020-11-17T12:23:15.000Z",
            step_count: 4,
            can_run: true,
            integrator_email: "reetututeja@email.arizona.edu",
            app_type: "DE",
            rating: {
                average: 4.5,
                total: 2,
            },
        },
        {
            integration_date: "2018-02-02T22:35:49.000Z",
            description:
                "Joins two or more files together head to tail using latest Dockerized version of cat.",
            deleted: false,
            pipeline_eligibility: {
                is_valid: true,
                reason: "",
            },
            is_favorite: true,
            integrator_name: "rwalls",
            beta: true,
            permission: "read",
            isBlessed: false,
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Concatenate Multiple Files",
            limitChecks: {
                canRun: true,
                results: [],
            },
            system_id: "de",
            overall_job_type: "executable",
            is_public: true,
            id: "77830f32-084a-11e8-a871-008cfa5ae621",
            edited_date: "2018-02-02T22:35:49.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "rlwalls2008@gmail.com",
            app_type: "DE",
            rating: {
                average: 5,
                total: 1,
            },
        },
        {
            integration_date: "2014-04-11T18:03:23.000Z",
            description:
                "Concatenate multiple files. Compatible with Workflows in the DE.",
            deleted: false,
            pipeline_eligibility: {
                is_valid: true,
                reason: "",
            },
            is_favorite: false,
            integrator_name: "Roger Barthelson",
            beta: true,
            permission: "read",
            isBlessed: false,
            can_favor: true,
            disabled: false,
            can_rate: true,
            name: "Concatenate 2 Files-workflow edition.",
            limitChecks: {
                canRun: true,
                results: [],
            },
            system_id: "de",
            overall_job_type: "executable",
            is_public: true,
            id: "af334df2-ad6e-4bf4-b7e8-5686525b63b0",
            edited_date: "2021-06-23T22:56:57.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "rogerab@email.arizona.edu",
            app_type: "DE",
            wiki_url:
                "http://pods.iplantcollaborative.org/wiki/display/DEapps/Concatenate+2+Files-workflow+edition.",
            rating: {
                average: 3.3333333333333335,
                total: 3,
            },
        },
        {
            description:
                "Counts and summarizes the number of lines, words, and bytes in a target file",
            deleted: false,
            pipeline_eligibility: {
                is_valid: true,
                reason: "",
            },
            is_favorite: true,
            integrator_name: "Matthew Vaughn",
            beta: false,
            permission: "read",
            isBlessed: false,
            can_favor: true,
            disabled: true,
            can_rate: true,
            name: "Word Count",
            limitChecks: {
                canRun: true,
                results: [],
            },
            system_id: "de",
            overall_job_type: "executable",
            is_public: true,
            id: "c7f05682-23c8-4182-b9a2-e09650a5f49b",
            edited_date: "2021-06-23T22:51:50.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "vaughn@iplantcollaborative.org",
            app_type: "DE",
            wiki_url:
                "https://pods.iplantcollaborative.org/wiki/display/DEapps/Word%20Count",
            rating: {
                average: 4.181818181818182,
                total: 11,
            },
        },
        {
            integration_date: "2018-06-19T20:09:42.000Z",
            description: "[no description provided]",
            deleted: false,
            pipeline_eligibility: {
                is_valid: true,
                reason: "",
            },
            is_favorite: false,
            integrator_name: "Sarah Roberts",
            permission: "read",
            can_favor: false,
            disabled: false,
            can_rate: false,
            name: "Word Count DE-2 0.0.3",
            limitChecks: {
                canRun: true,
                results: [],
            },
            system_id: "tapis",
            is_public: false,
            id: "word-count-de-2-0.0.3",
            edited_date: "2018-06-19T20:09:42.000Z",
            step_count: 1,
            can_run: true,
            integrator_email: "sarahr@cyverse.org",
            app_type: "External",
            wiki_url: "",
            rating: {
                average: 0,
                total: 0,
            },
        },
    ],
};
export const analysesSearchResp = {
    analyses: [
        {
            description: "",
            name: "DE_Word_Count_analysis1",
            can_share: true,
            username: "sriram@iplantcollaborative.org",
            app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
            system_id: "de",
            app_disabled: false,
            batch: false,
            enddate: "1597151491081",
            status: "Completed",
            id: "0cb5fa4c-dbd4-11ea-a163-62d47aced14b",
            startdate: "1597151437252",
            app_description: "Counts the number of words in a file",
            wiki_url: "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
            notify: true,
            resultfolderid:
                "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-08-11-13-10-37.2",
            app_name: "DE Word Count",
        },
    ],
    timestamp: "1597157985945",
    total: 1,
    "status-count": [{ count: 1, status: "Completed" }],
};
