const ids = {
    ADMIN_JOIN_TEAM: {
        ADMIN: "admin",
        APPROVE: "radioApprove",
        DENY: "radioDeny",
        DENY_MSG: "denyMsg",
        DIALOG: "adminJoinTeamDlg",
        PRIVILEGE_SELECT: "privilegeSelect",
        READ: "member",
        SUBMIT_BTN: "submitBtn",
    },

    APPROVE_BTN: "approveBtn",
    BASE_DEBUG_ID: "notifications",
    CANCEL_BTN: "cancelBtn",
    CATEGORY: "categoryColumn",
    CHECKBOX: "checkbox",
    COMMENT: "commentColumn",
    CREATED_DATE: "dateColumn",
    DELETE_BTN: "deleteBtn",
    DENY_BTN: "denyBtn",
    DENY_MSG: "denyMsg",
    DENY_REQUEST_DLG: "denyRequestDlg",
    FILTER: "categoryCbo",
    JOIN_REQUEST_DLG: "joinRequestDlg",
    JOIN_REQUEST_VIEW: "view",
    LOADING_SKELETON: "loadingSkeleton",
    MARK_ALL_READ: "mark-all-read",
    MARK_ALL_SEEN_BTN: "markAllSeenBtn",
    MESSAGE: "messageColumn",
    NOTIFICATION_FILTER: "notificationFilter",
    NOTIFICATION_VIEW: "notificationView",
    NOTIFICATIONS_HEADER: "notificationsTab",
    NOTIFICATIONS_MENU: "notification-menu",
    OK_BTN: "okBtn",
    PANEL: "panel",
    REFRESH_BTN: "refreshBtn",
    REQUEST_HISTORY_DLG: "requestHistoryDlg",
    SET_PRIVILEGE_DLG: "setPrivilegeDlg",
    STATUS: "requestStatusColumn",
    SIGN_IN_ERR_DIALOG: "signInErrorDialog",
    TIME_STAMP: "time-stamp",
    TOOLBAR: "toolbar",
    VICE_HEADER: "runningViceTab",
    VIEW_ALL_NOTIFICATIONS: "view-all-notifications",
};

export default ids;
