export const listing = {
    analyses: [
        {
            description: "",
            name: "DE_Word_Count_analysis1",
            can_share: true,
            username: "sriram@iplantcollaborative.org",
            app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
            system_id: "de",
            app_disabled: false,
            batch: false,
            enddate: "1587023391999",
            status: "Completed",
            id: "c1e6c4e8-7fb6-11ea-be0a-c2a97b34bb42",
            startdate: "1587023349739",
            app_description: "Counts the number of words in a file",
            wiki_url: "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
            notify: true,
            resultfolderid:
                "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-16-07-49-09.7",
            app_name: "DE Word Count",
        },
        {
            description: "",
            name: "DE_Word_Count_analysis1",
            can_share: true,
            username: "sriram@iplantcollaborative.org",
            app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
            system_id: "de",
            app_disabled: false,
            batch: false,
            enddate: "1587022622645",
            status: "Completed",
            id: "fbfa7d8e-7fb4-11ea-9730-c2a97b34bb42",
            startdate: "1587022588272",
            app_description: "Counts the number of words in a file",
            wiki_url: "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
            notify: true,
            resultfolderid:
                "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-16-07-36-28.2",
            app_name: "DE Word Count",
        },
        {
            description: "",
            name: "DE_Word_Count_analysis1",
            can_share: true,
            username: "sriram@iplantcollaborative.org",
            app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
            batch_status: { total: 9, completed: 9, running: 0, submitted: 0 },
            system_id: "de",
            app_disabled: false,
            batch: true,
            enddate: "1586950384244",
            status: "Completed",
            id: "a5e68c74-7f0c-11ea-be65-c2a97b34bb42",
            startdate: "1586950288785",
            app_description: "Counts the number of words in a file",
            notify: true,
            resultfolderid:
                "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-15-11-31-27.4",
            app_name: "DE Word Count",
        },
        {
            description: "",
            name: "ten-rules-jupyter_analysis1",
            can_share: true,
            username: "sriram@iplantcollaborative.org",
            app_id: "8ec235d8-f173-11e9-a56f-008cfa5ae621",
            system_id: "de",
            app_disabled: false,
            batch: false,
            enddate: "0",
            status: "Running",
            id: "8712ea7c-7f0c-11ea-be65-c2a97b34bb42",
            startdate: "1586950235151",
            app_description:
                "Jupyter Notebooks for: Ten simple rules for writing and sharing computational analyses in Jupyter Notebooks. Rule A, Birmingham A, Zuniga C, Altintas I, Huang SC, Knight R, Moshiri N, Nguyen MH, Rosenthal SB, Pérez F, Rose PW. PLoS Comput Biol. 2019 Jul 25;15(7):e1007007. doi: 10.1371/journal.pcbi.1007007",
            interactive_urls: ["https://a444587f3.cyverse.run:4343"],
            notify: true,
            resultfolderid:
                "/iplant/home/sriram/analyses_qa/ten-rules-jupyter_analysis1-2020-04-15-11-30-35.1",
            app_name: "ten-rules-jupyter",
        },
        {
            description: "",
            name: "DE_Word_Count_analysis1",
            can_share: true,
            username: "sriram@iplantcollaborative.org",
            app_id: "67d15627-22c5-42bd-8daf-9af5deecceab",
            system_id: "de",
            app_disabled: false,
            batch: false,
            enddate: "1586786169987",
            status: "Completed",
            id: "727c6ffe-7d8e-11ea-bedd-c2a97b34bb42",
            startdate: "1586786134287",
            app_description: "Counts the number of words in a file",
            wiki_url: "https://wiki.cyverse.org/wiki/display/DEapps/Word+Count",
            notify: true,
            resultfolderid:
                "/iplant/home/sriram/analyses_qa/DE_Word_Count_analysis1-2020-04-13-13-55-34.2",
            app_name: "DE Word Count",
        },
    ],
    timestamp: "1587108592817",
    total: 5,
};
