const ids = {
    EDIT_METADATA_FORM: "editMetadataDialog",
    METADATA_TEMPLATE_LISTING: "metadataTemplateListing",
    METADATA_TEMPLATE_VIEW: "metadataTemplate",

    AVU_GRID: "avuGrid",
    AVU_GRID_CHECKBOX: "avuGridCheckbox",
    AVU_ATTR: "attr",
    AVU_VALUE: "value",
    AVU_UNIT: "unit",
    AVU_AVUS: "avus",

    BUTTONS: {
        ADD: "addBtn",
        CONFIRM: "confirmBtn",
        COPY_METADATA: "copyBtn",
        DELETE: "deleteBtn",
        DONE: "doneBtn",
        DOWNLOAD: "downloadBtn",
        EDIT: "editBtn",
        EXPAND: "expand",
        HELP: "help",
        INFO: "info",
        IMPORT_IRODS_METADATA: "importIRODSMetadata",
        SAVE: "saveBtn",
        SAVE_METADATA_TO_FILE: "saveMetadataToFile",
        VIEW_TEMPLATES: "templates",
        VIEW_USER_METADATA: "viewUserMetadata",
        VIEW_IRODS_METADATA: "viewIRODSMetadata",
    },

    COL_ACTIONS: "actions",
    COL_HEADER: "colHeader",
    DIALOG: "dialog",
    TITLE: "title",
    CANCEL_BUTTON: "cancelButton",
    COPY_DIALOG: "copyDialog",
    COPY_BUTTON: "copyButton",
    COPY_DESTINATIONS: "copyDestinations",
    SELECTED_RESOURCES: "selectedResources",
    METADATA_FILE: "metadataFile",
    BULK_METADATA_DIALOG: "bulkMetadataDialog",
};

export default ids;
