export default {
    EDIT_METADATA_FORM: "editMetadataDialog",
    METADATA_TEMPLATE_VIEW: "metadataTemplate",

    AVU_GRID: "avuGrid",
    AVU_ATTR: "attr",
    AVU_VALUE: "value",
    AVU_UNIT: "unit",
    AVU_AVUS: "avus",
    BUTTONS: {
        ADD: "addBtn",
        CLOSE: "closeBtn",
        CLOSE_ICON: "closeIconBtn",
        DELETE: "deleteBtn",
        EDIT: "editBtn",
        EXPAND: "expand",
        HELP: "help",
        IMPORT_IRODS_METADATA: "importIRODSMetadata",
        SAVE: "saveBtn",
        SAVE_METADATA_TO_FILE: "saveMetadataToFile",
        VIEW_TEMPLATES: "templates",
    },
    COL_ACTIONS: "actions",
    COL_HEADER: "colHeader",
    DIALOG: "dialog",
    TITLE: "title",
};
