export default {
    ADD_BUTTON: "addButton",
    CANCEL_BUTTON: "cancelButton",
    DETAILS_DRAWER: "detailsDrawer",
    DETAILS_MENU_ITEM: "detail",
    DETAILS_TAB: "detailsTab",
    EDIT_MENU_ITEM: "edit",
    EDIT_SUBSCRIPTION_FORM: {
        PLAN_NAME: "planName",
        PLAN_TYPES: "planTypes",
        USERNAME: "username",
    },
    END_DATE: "endDate",
    END_DATE_CELL: "endDateCell",
    ERROR_DLG: "errorDialog",
    ERROR_HANDLER: "errorHandler",
    LISTING_TABLE: "listingTable",
    NEW_SUBSCRIPTION_STATUS: "newSubscriptionStatus",
    PLAN_NAME: "planName",
    PLAN_NAME_CELL: "planNameCell",
    ROW_DOT_MENU: "rowDotMenu",
    SAVE_BUTTON: "saveButton",
    SEARCH_FIELD: "searchField",
    SELECTED_USER: "selectedUser",
    START_DATE: "startDate",
    START_DATE_CELL: "startDateCell",
    SUBSCRIPTION_DETAILS: "subscriptionDetails",
    TOOLBAR: "toolbar",
    USERNAME: "username",
    USERNAME_CELL: "usernameCell",
};
