export default {
    ANALYSES_SEARCH_RESULTS_TAB: "analysesSearchResultsTab",
    ANALYSES_SEARCH_OPTION: "analysesSearchOption",
    APPS_SEARCH_RESULTS_TAB: "appsSearchResultsTab",
    APPS_SEARCH_OPTION: "appsSearchOption",
    DATA_SEARCH_RESULTS_TAB: "dataSearchResultsTab",
    DATA_SEARCH_OPTION: "dataSearchOption",
    TEAM_SEARCH_OPTION: "teamSearchOption",
    TEAM_SEARCH_RESULTS_TAB: "teamSearchResultsTab",
    GLOBAL_SEARCH_FIELD: "globalSearchField",
    SEARCH: "search",
    SEARCH_FILTER_MI: {
        ALL: "all",
        ANALYSES: "analyses",
        APPS: "apps",
        DATA: "data",
        TEAMS: "teams",
    },
    SEARCH_FILTER_MENU: "searchFilterMenu",
    SEARCH_INPUT_FILED: "searchInput",
    TABLE_VIEW: "tableView",
    VIEW_ALL: "viewAll",
};
