const ids = {
    ANALYSES_EMAIL_NOTIFICATION_SWITCH: "analysesEmailNotificationSwitch",
    PERIODIC_EMAIL_NOTIFICATION_SWITCH: "periodicEmailNotificationSwitch",
    PERIODIC_NOTIFICATION_PERIOD: "periodicNotificationPeriod",
    ANALYSES_KB_SHORTCUT_TEXT: "analysesKbShortcutText",
    APPS_KB_SHORTCUT_TEXT: "appKbShortcutText",
    BROWSE_BUTTON: "browseButton",
    CANCEL_BUTTON: "cancelButton",
    DATA_KB_SHORTCUT_TEXT: "dataKbShortcutText",
    DEFAULT_OUTPUT_FOLDER: "defaultOutputFolder",
    EMAIL: "email",
    FOLDER_SELECTION_DRAWER: "folderSelectionDrawer",
    GENERAL: "general",
    HPC_LOGIN_PROMPT_SWITCH: "hpcLoginPromptSwitch",
    HPC_WAIT_TIMES_SWITCH: "hpcWaitTimesSwitch",
    KB_SHORTCUTS: "keyboarShortcuts",
    LOADING_PROGRESS: "circularProgress",
    NOTIFICATIONS_KB_SHORTCUT_TEXT: "notificationsKbShortcutText",
    OK_BUTTON: "okButton",
    PREFERENCES: "preferences",
    REMEMBER_LAST_PATH_SWITCH: "rememberLastPastSwitch",
    RESET_HPC_BTN: "resetHpcBtn",
    RESTORE_DEFAULT_BUTTON: "restoreDefaultButton",
    SAVE_PREFERENCES_BUTTON: "savePreferencesButton",
    URL_IMPORT_EMAIL_NOTIFICATION_SWITCH: "urlImportEmailNotificationSwitch",
    WEBHOOK_PREF: "webhookPreferences",
    WEBHOOK_URL_TEXT: "webhookURLText",
    WEBHOOK_TYPES_SELECT: "webhookTypesSelect",
    WEBHOOK_TEST_BTN: "webhookTestBtn",
    WEBHOOK_TOPIC_SWITCH: "webhookTopicSwitch",
};

export default ids;
