export default {
    ARCHIVE: "Archive",
    BARCODE_FILE: "BarcodeFile",
    BINARY: "Binary",
    BIOLOGICAL_MODEL: "BiologicalModel",
    EXPRESSION_DATA: "ExpressionData",
    FILE: "File",
    GENOMIC_ANNOTATION: "GenomicAnnotation",
    GRAPH_FILE: "GraphFile",
    IMAGE: "Image",
    MULTIPLE_SEQUENCE_ALIGNMENT: "MultipleSequenceAlignment",
    NUCLEOTIDE_OR_PEPTIDE_SEQUENCE: "NucleotideOrPeptideSequence",
    PLAIN_TEXT: "PlainText",
    RECONCILE_TAXA: "ReconcileTaxa",
    REFERENCE_GENOME: "ReferenceGenome",
    REFERENCE_SEQUENCE: "ReferenceSequence",
    REFERENCE_ANNOTATION: "ReferenceAnnotation",
    SEQUENCE_ALIGNMENT: "SequenceAlignment",
    STRUCTURE: "Structure",
    STRUCTURED_TEXT: "StructuredText",
    TRAIT_FILE: "TraitFile",
    TREE_FILE: "TreeFile",
    VARIANT_DATA: "VariantData",
    TABULAR_DATA: "TabularData",
    UNSPECIFIED: "Unspecified",
};
