// constants that define navigation routes
export default {
    ADMIN: "admin",
    ANALYSES: "analyses",
    APPS: "apps",
    ERROR: "error",
    DASHBOARD: "dashboard",
    DATA: "data",
    DETAILS: "details",
    LOGIN: "login",
    LOGOUT: "logout",
    MORE: "more",
    NOTIFICATIONS: "notifications",
    NOTIFICATION_WS: "/websocket/notifications",
    REF_GENOMES: "refgenomes",
    RELAUNCH: "relaunch",
    SEARCH: "search",
    SETTINGS: "settings",
    VICE: "vice",
    TOOLS: "tools",
    YOUTUBE_EMBED_BASE: "https://youtu.be",
};
