export default {
    LOADING_SKELETON: "loadingSkeleton",
    PAGE_SIZE_MENU: "pageSizeMenu",
    PAGINATION_TOOLBAR: "paginationToolbar",
    ERROR_HANDLER: "errorHandler",
    USER: "user",
    BROWSER: "browser",
    OS: "os",
    HOST: "host",
    SIGN_IN_LINK: "signInLink",
    REGISTER_LINK: "registerLink",
    REQUESTED_URL: "requestedURL",
    STATUS_CODE: "statusCode",
    ERROR_CODE: "errorCode",
    REASON: "reason",
    CONTACT_SUPPORT_BUTTON: "contactSupportBtn",
    GRID_VIEW_BTN: "gridViewBtn",
    TABLE_VIEW_BTN: "tableViewBtn",
    ERROR_DLG: "errorDialog",

    DIALOG: {
        CANCEL: "cancel",
        CONFIRM: "confirm",
        TITLE: "title",
    },
};
