export default {
    TYPE: "type",
    SYSTEM_ID: "system-id",
    APP_ID: "app-id",
    STATE: "state",
    APPS: "apps",
    DATA: "data",
    AGAVE: "agave",
    QUICK_LAUNCH: "quick-launch",
    QUICK_LAUNCH_ID: "quick-launch-id",
    QUICK_LAUNCH_EMBED_ICON: "Powered-By-CyVerse-blue.svg",
    APP_NAME_RESTRICTED_CHARS: ":@/\\|^#;[]{}<>",
    APP_NAME_RESTRICTED_STARTING_CHARS: "~.$",
    DOCUMENTATION_TEMPLATE_URL: "app-doc-template.txt",
};
