export default {
    APP_NAME: "appName",
    DOT_MENU: "dotMenu",
    APP_INFO: "appInfo",
    FAVORITES: "favorites",
    APP_COMMENTS: "appComments",
    CARD: "card",
    APP_QUICK_LAUNCH: "appQuickLaunch",
    LISTING_TABLE: "listingTable",
    HEADER: "header",
    GRID_VIEW_BTN: "gridViewBtn",
    TABLE_VIEW_BTN: "tableViewBtn",
    TOOLTIP: "tooltip",
    APP_NAVIGATION: "appNavigation",
    APP_CATEGORIES: "appCategories",
    APP_CATEGORIES_MENU: "appCategoriesMenu",
    APP_CATEGORIES_MENU_ITEM: "appCategoriesMenuItem",
    checkbox: "checkbox",
    integratorName: "integratorName",
    RATING: "rating",
    SYSTEM_ID: "systemId",
    APP_STATUS_ICON: "appStatusIcon",
    BROWSE_ALL_APPS: "browseAllApps",
    AGAVE_AUTH_PROMPT_DIALOG: "agaveAuthPromptDialog",
    AGAVE_AUTH_PROMPT_DIALOG_AUTH_BTN: "authenticateBtn",
    AGAVE_AUTH_PROMPT_DIALOG_DENY_BTN: "notNowBtn",
    AGAVE_AUTH_PROMPT_DIALOG_TITLE: "agaveAuthPromptDialogTitle",
};
