const ids = {
    ADMIN_APPS_FILTER: "adminAppsFilter",
    ADMIN_APPS_FILTER_FIELD: "adminAppsFilterField",
    ADMIN_APPS_SEARCH: "adminAppsSearch",
    APP_NAME: "appName",
    APP_TYPE: "appType",
    APP_VERSION_SELECTION: "appVersionSelection",
    ACCESS_REQUEST_DLG: "accessRequestDlg",
    DOT_MENU: "dotMenu",
    DOCUMENTATION_DLG: "appDocDlg",
    DOC_MARKDOWN: "docMarkdown",
    DOC_TEXT: "docText",
    APP_INFO: "appInfo",
    FAVORITES: "favorites",
    APP_COMMENTS: "appComments",
    CARD: "card",
    CLOSE_BTN: "closeButton",
    COPY_MENU_ITEM: "copy",
    CREATE_APP_BTN: "createAppButton",
    CREATE_APP_MENU_ITEM: "createAppMenuItem",
    CREATE_APP_VERSION_MENU_ITEM: "createAppVersionMenuItem",
    CREATE_MENU_ITEM: "createMenuItem",
    CREATE_WORKFLOW_MENU_ITEM: "createWorkflowMenuItem",
    EDIT_APP_VERSION_ORDER_MENU_ITEM: "editAppVersionOrderMenuItem",
    DIALOG: "dialog",
    APP_SAVED_LAUNCH: "appSavedLaunch",
    LISTING_TABLE: "listingTable",
    HEADER: "header",
    GRID_VIEW_BTN: "gridViewBtn",
    TABLE_VIEW_BTN: "tableViewBtn",
    TOOLTIP: "tooltip",
    APPS_FILTER: "appsFilter",
    APPS_TOOLBAR: "appsToolbar",
    APPS_NAVIGATION: "appNavigation",
    APPS_CATEGORIES: "appCategories",
    APPS_CATEGORIES_MENU: "appCategoriesMenu",
    APPS_CATEGORIES_MENU_ITEM: "appCategoriesMenuItem",
    checkbox: "checkbox",
    integratorName: "integratorName",
    RATING: "rating",
    SYSTEM_ID: "systemId",
    APP_STATUS_ICON: "appStatusIcon",
    BROWSE_ALL_APPS: "browseAllApps",
    AGAVE_AUTH_PROMPT_DIALOG: "agaveAuthPromptDialog",
    AGAVE_AUTH_PROMPT_DIALOG_AUTH_BTN: "authenticateBtn",
    AGAVE_AUTH_PROMPT_DIALOG_DENY_BTN: "notNowBtn",
    AGAVE_AUTH_PROMPT_DIALOG_TITLE: "agaveAuthPromptDialogTitle",
    DETAILS_BTN: "detailsBtn",
    DETAILS_DRAWER: "appDetailsDrawer",
    DETAILS_MENU_ITEM: "details",
    DETAILS_TAB: "detailsTab",
    DOCS_TAB: "documentationTab",
    ADD_TO_BAG_BTN: "addToBagBtn",
    ADD_TO_BAG_MENU_ITEM: "addToBag",
    TOOLS_INFO_TAB: "toolsInfoTab",
    TOOLS_BTN: "manageToolsButton",
    MANAGE_TOOLS_DIVIDER: "manageToolsDivider",
    TOOLS_MENU_ITEM: "manageToolsMenuItem",
    PANEL: "panel",
    APP_DETAILS: "appDetails",
    APP_FAVORITE: "appFavorite",
    APP_UNFAVORITE: "appUnFavorite",
    TOOLS_USED: "toolsUsed",
    AVERAGE_RATING: "averageRating",
    FILTER_MENU_ITEM: "filter",
    VIEW_ALL_APPS: "viewAllApps",
    SAVED_LAUNCH_MENU_ITEM: "savedLaunchMI",
    DELETE: "delete",
    DISABLE: "disable",
    DOC_MENU_ITEM: "documentation",
    EDIT_MENU_ITEM: "edit",
    SEARCH: "search",

    SAVED_LAUNCH: {
        NAME: "name",
        DESCRIPTION: "description",
        PUBLIC: "public",
        CREATE: "createSavedLaunch",
        CANCEL: "cancelCreateSavedLaunch",
        USE_SAVED_LAUNCH: "useQL",
        SHARE_SAVED_LAUNCH: "shareSavedLaunch",
        EMBED_SAVED_LAUNCH: "embedSavedLaunch",
    },

    EDIT_BTN: "editButton",
    SAVE_BTN: "saveButton",
    SUBMIT_BTN: "submitButton",
    CANCEL_BTN: "cancelButton",

    ADMIN_DETAILS: {
        NAME: "name",
        DESCRIPTION: "description",
        INTEGRATOR: "integrator",
        INTEGRATOR_EMAIL: "integratorEmail",
        DELETED: "deleted",
        DISABLED: "disabled",
        BETA: "beta",
        BLESSED: "blessed",
        WIKI_URL: "wikiURL",
        DOCUMENTATION: "documentation",
        HTCONDOR_EXTRA_REQS: "htcondorExtraReqs",
    },

    APP_STEPPER: {
        STEP_BTN: "stepButton",
        STEP_BACK: "stepBackButton",
        STEP_NEXT: "stepNextButton",
    },

    RUN_ERROR_DLG: "runErrorDlg",

    PUBLICATION_REQUESTS: {
        BASE_ID: "publicationRequests",
        TOOLS_USED_DIALOG: "toolsUsedDialog",
        TOOLS_USED_LISTING: "toolsUsedListing",
        REQUEST_LISTING: "requestListing",
    },

    PUBLISH_DLG: "publishDlg",
    PUBLISH_MENU_ITEM: "publishMenuItem",

    PUBLISH: {
        NAME: "name",
        DESCRIPTION: "description",
        INPUT: "inputDescription",
        PARAMS: "paramsDescription",
        OUTPUT: "outputDescription",
        LINK: "link",
        LINK_DEL_BTN: "deleteLinkBtn",
        LINK_ADD_BTN: "linkAddBtn",
        LICENSE_TYPE: "licenseType",
        LICENSE_LINK: "licenseLink",
    },

    SELECT_COLLECTION_DLG: "selectCollectionDlg",
    INSTANT_LAUNCH_BTN: "instantLaunchBtn",
    INSTANT_LAUNCH_MI: "instantLaunchMI",
};

export default ids;
