name: skaffold-build-prerelease
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
jobs:
  pipeline:
    name: Skaffold Docker build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v3
    - name: Harbor Login
      id: harbor_login
      uses: docker/login-action@v2
      with:
        registry: harbor.cyverse.org
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Install Kubernetes Tools
      id: install_k8s_tools
      uses: yokawasa/action-setup-kube-tools@v0.9.2
    - name: Build Docker images
      id: build
      run: |
        skaffold build --file-output build.json
    - name: Build manifest tarball
      id: build_manifest_tarball
      run: |
        tar -czpvf deploy-info.tar.gz build.json skaffold.yaml k8s
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build.json,deploy-info.tar.gz"
        prerelease: true
